### ISSUE TITLE
关于hexo-theme-indigo的一些建议

### ISSUE THREAD

**Issue by TAMMENY** [yscoder/hexo-theme-indigo#1]
1. less编译问题。建议在README.md写明需要安装hexo-renderer-less及安装方法，可以避免一些新手踩坑，好比我；

2. 默认配置文件问题。建议在主题的_config.yml里面增加邮箱配置项，并且将layout/_partial/left-col.ejs里的`<%- mail_to(config.email, config.email, {class: 'mail'}) %>`改成`<%- mail_to(config.email, theme.email, {class: 'mail'}) %>`，因为某些用户的博客配置文件没有email这个配置项目；

3. tags页面问题。主题的侧栏有tags的入口，某些新用户可能还没有建立tags页面，建议声明要使用`hexo new page tags`创建一个新页面并且将页面类型设置为tages，如：
`---
title: tags
date: 2016-01-30 13:01:19
type: "tags"
---`

感谢您的主题，很赞。

**Comment by yscoder** [comment]
谢谢你的建议，已更新。
