### ISSUE TITLE
[Feature Request] Canonical Link

### ISSUE THREAD

**Issue by NoahDragon** [yscoder/hexo-theme-indigo#100]
不知道作者能否实现Canonical Link在这个主题里呢？这样不用再下插件了。

**Comment by yscoder** [comment]
这对我来说又是一个新的关键词，刚才查了下资料，我理解的是：Canonical Link 就是给搜索引擎的重定向指令。
这样我应该只需要在模版中加一个这样的标签和基于一定格式或正则的 URL 配置项就可以吧。

**Comment by NoahDragon** [comment]
确实是针对搜索引擎的优化的。主要是让搜索引擎将不同URL指向同一个设定的URL上。

NexT 主题有这个实现 https://github.com/iissnan/hexo-theme-next/blob/master/layout/_partials/head.swig#L99 

似乎是一定格式即可。

**Comment by yscoder** [comment]
我想了解下，在博客中需要使用 Canonical Link 的场景。

看了 NexT 的实现，我猜想主要是为了应对以下问题：

1. 博客部署在不同的域名上，如:  `site.com` 和 `mysite.com`
2. 博客部署在同个域名的不同子域上，如 `site.com` 和 `www.site.com`
3. 博客部署在同个域名的不同文件目录中，如 `site.com` 和 `site.com/blog`

通过 Canonical Link，使搜索引擎最终到达的页面永远是基于你在 config.yml 中定义的 url。
这样就可以汇集不同来路的流量到你期望的页面。

不知道我理解的对不对？

**Comment by NoahDragon** [comment]
不能再对了 👍 而且已经看到含括在1.1版本中了，感谢。
