### ISSUE TITLE
Tag 页面的 tabs-bar中的tag list more遮挡住最后一个tab

### ISSUE THREAD

**Issue by weiyf** [yscoder/hexo-theme-indigo#102]
Tag 页面的 `tabs-bar`中的`tag list more`遮挡住最后一个tab
如图：
![2016-10-29 10-06-55](https://cloud.githubusercontent.com/assets/12067656/19826527/78a1163a-9dbf-11e6-8aa0-ff98c7e4a98d.png)

**Comment by yscoder** [comment]
更新了 tabs-bar 中的数据排列，保持当前项永远在视野中。
