### ISSUE TITLE
手机浏览器进入博客，一直在加载，导致无法点击侧边栏

### ISSUE THREAD

**Issue by weiyf** [yscoder/hexo-theme-indigo#103]
手机浏览器进入博客，一直在加载，导致无法点击侧边栏

**Comment by yuangezhizao** [comment]
我现在也是如此

**Comment by yscoder** [comment]
最近真是 ES6 写多了，写了个这样的函数，怪不得 PC 上一直找不到原因。😅

![image](https://cloud.githubusercontent.com/assets/12295378/19835953/451edc38-9ece-11e6-9854-57ce5e2184be.png)
