### ISSUE TITLE
评论配置的问题,配置好了多说.但是还是不出现评论框

### ISSUE THREAD

**Issue by Chanran** [yscoder/hexo-theme-indigo#105]
```
<script>
var duoshuoQuery = {short_name:'blueBlog', theme: 'none'}
</script>
```
以上是[我的文章](https://chanran.github.io/2016/11/01/css3动画笔记/)的源码里找到的.

1.配置好了多说:站点叫 **blueBlog**
2.在_config.yml写了:```duoshuo: blueBlog```

**Comment by yscoder** [comment]
那 `http://blueblog.duoshuo.com/admin/` 是你的多说后台地址吗？
如果不是，说明你的  `short_name` 不正确。

**Comment by Chanran** [comment]
懂了,我还以为是我自己设定的站点名称...我觉得应该在wiki那里写个例子好一点,有点误导...(:

**Comment by yscoder** [comment]
ok
