### ISSUE TITLE
Categories paginate 

### ISSUE THREAD

**Issue by NoahDragon** [yscoder/hexo-theme-indigo#106]
![image](https://cloud.githubusercontent.com/assets/5704064/19900467/ff410f02-a039-11e6-9fa2-f91095730c67.png)
我的一个分类下有多余一页的文章（每页为10，并未在config file中设置），在categories中无法选择下一页。

网页链接：https://cn.abnerchou.me/categories/%E8%AF%84%E8%AF%B4/

**Comment by yscoder** [comment]
分类里面可以分页了，但是 ` /categories` 路径不是 hexo-generator 生成的，无法简单调用 `hexo-pagination` 分页。
之后的版本我考虑由前端控制伪分页或滚动加载，也有可能创建 hexo-generator 类插件来实现。

**Comment by NoahDragon** [comment]
非常感谢！
