### ISSUE TITLE
TOC一小问题

### ISSUE THREAD

**Issue by yuangezhizao** [yscoder/hexo-theme-indigo#110]
观察[此页面](https://blog.yuangezhizao.cn/2016/Mac/Mac%E4%B8%8BGit%E7%9A%84%E4%BD%BF%E7%94%A8/)，TOC中的`0x00.安装SourceTree`刚开始分成了两行，页面下拉后会变回为一行，能否统一一下，谢谢！

**Comment by NoahDragon** [comment]
同样有此问题~

**Comment by yuangezhizao** [comment]
感谢修复！
