### ISSUE TITLE
一格式问题

### ISSUE THREAD

**Issue by yuangezhizao** [yscoder/hexo-theme-indigo#111]
观察[此页面](https://blog.yuangezhizao.cn/2016/Git/Git%E7%9A%84%E4%BD%BF%E7%94%A8/)，`6.3 关于HostKey`处，文字部分超过限制直接跑到了右侧，请问原因出在哪里，谢谢？

**Comment by NoahDragon** [comment]
我这看正常啊~
![image](https://cloud.githubusercontent.com/assets/5704064/20006990/9e4a328a-a270-11e6-8ac6-eec9fe53dbbf.png)

**Comment by yscoder** [comment]
![image](https://cloud.githubusercontent.com/assets/12295378/20008268/ddcbee52-a2da-11e6-9777-027ede070a95.png)

`ol` 未将其余 `li` 包裹在内，能否提供这篇文章的 MD 源文件，我好排查原因。
可以发我邮箱，634206017@qq.com。

**Comment by yuangezhizao** [comment]
抱歉我没说明白，是TOC对应的正文部分
![qq20161105-0](https://cloud.githubusercontent.com/assets/16861681/20012923/38dddd80-a2ec-11e6-84b9-a2625580a9e3.png)

**Comment by yscoder** [comment]
## 内容溢出的问题

已解决，书写建议：类似此类内容应该以代码块格式书写。

## TOC 渲染

我看了 MD，对标题标号排列不能理解，从 4 级标题 3.1.2 起步接着是 3 级标题 3.2。hexo 应该是把文章内的第一个标题当作 toc 的第一层级去渲染了。

书写建议：保持文章内的所有标题级别  <= 第一个标题的级别。

**Comment by yuangezhizao** [comment]
感谢建议，其实这篇文章是如正文末尾第一个原文地址所示转自“https://coding.net/help/doc/git/git.html”，内容稍加修改而得。至于TOC则是自己删改不当而产生了问题。

**Comment by yscoder** [comment]
👌
