### ISSUE TITLE
tag页面的问题

### ISSUE THREAD

**Issue by xdcxdc** [yscoder/hexo-theme-indigo#113]
1\. html 的 `<title>` 内用的仍然是 `'Tag'`，而不是 `theme.tags_title`
2\. 标签的大小写多处不一致。 
 `<li class="article-tag-list-item">` 和 `<a class="tags-list-item waves-effect waves-button waves-light">` 内，如果首字母不是大写，会被改为首字母大写，否则保持md文件内的原样。
 `<h1 class="title">` 这里则全部被改为首字母大写其余小写，如 `GitHub` 被改为 `Github` 。
 只有`<title>` 内是md文件里原始的大小写形式。

**Comment by yscoder** [comment]
这都被你发现了
