### ISSUE TITLE
https访问站点，多说评论无法显示

### ISSUE THREAD

**Issue by yuangezhizao** [yscoder/hexo-theme-indigo#114]
## http访问正常，https访问异常。
> 测试时请及时刷新页面

**Comment by yscoder** [comment]
我这边测试正常

**Comment by yuangezhizao** [comment]
我用的FireFox，比如此页面[https://imys.net/20161031/text-transform-capitalize-not-working.html](https://imys.net/20161031/text-transform-capitalize-not-working.html)，进入后刷新下，评论框就不见了。
![qq20161105-2](https://cloud.githubusercontent.com/assets/16861681/20029488/3f03a374-a388-11e6-966f-f81476bcffb6.png)

**Comment by yscoder** [comment]
我用 FireFox 测试也正常，应该不是协议问题。
打开你的网络请求，看看有没有多说相关的出现 404，多半是网络问题。

**Comment by yuangezhizao** [comment]
1. 特意下载了Chrome浏览器，问题仍然存在，说明不是浏览器的问题；
2. 在Chrome里打开网络请求，发现了个指向多说源站的https请求failed；
![qq20161105-3](https://cloud.githubusercontent.com/assets/16861681/20029614/adadb51e-a38b-11e6-8123-4085412b3e31.png)
3. 在FireFox里截图如图。
![qq20161105-4](https://cloud.githubusercontent.com/assets/16861681/20029628/f850ce80-a38b-11e6-8cdc-79429025e25f.png)

**Comment by yscoder** [comment]
如果仅仅是这个脚本文件请求 failed，可以本地化解决。这个脚本请求成功后，就会开始发起获取该页面文章所有评论的请求。如果你的网络连不上多说服务器，依然是无法正常使用。

**Comment by yuangezhizao** [comment]
手工访问`https://static.duoshuo.com/libs/embed.compat.js?24f8ca3f.js`，
1. FireFox
![qq20161105-5](https://cloud.githubusercontent.com/assets/16861681/20029774/a0953460-a390-11e6-8cb0-c5278a605940.png)
2. Chrome
![qq20161105-6](https://cloud.githubusercontent.com/assets/16861681/20029786/d58d1df4-a390-11e6-9a4b-9a7bc4f787b5.png)

看来确实是https连不上，但http访问却能连上，这就尴尬了。

**Comment by xdcxdc** [comment]
试了下，[https://static.duoshuo.com/libs/embed.compat.js?24f8ca3f.js](https://static.duoshuo.com/libs/embed.compat.js?24f8ca3f.js) 可以访问。可能是运营商问题。

**Comment by yuangezhizao** [comment]
我这里是沈阳移动，确实无法访问，刚用室友沈阳联通卡试了一下，发现可以访问。

**Comment by xdcxdc** [comment]
另外，AdBlock 也会默认屏蔽多说，最好在 `<div id="ds-waiting"></div>` 这里加上一句提示语，` AdBlock 可能会屏蔽多说，导致评论无法加载。如长时间加载不成功，请在当前网站禁用 AdBlock `

**Comment by xdcxdc** [comment]
@yscoder  
`https://static.duoshuo.com/libs/embed.compat.js?24f8ca3f.js` 会被 AdBlock 屏蔽，也就不会有 `<div id="ds-waiting"></div>` 出现了。
该脚本的 `last-modified` 是 `Fri, 25 Sep 2015 07:13:21 GMT` ，估计多说不会轻易修改。因此可以考虑将其本地化以防止屏蔽，并加上提示语。
