### ISSUE TITLE
手机端mathjax公式显示不完全

### ISSUE THREAD

**Issue by clatisus** [yscoder/hexo-theme-indigo#120]
![Markdown](http://p1.bpimg.com/1949/0b79d90d18f2fc98.png)

是响应式布局的锅？

**Comment by yscoder** [comment]
链接发一下

**Comment by clatisus** [comment]
@yscoder http://pages.clatisus.com/2016/11/09/2014-Multi-University-Training-Contest-1/
公式在最后面

**Comment by yscoder** [comment]
调正了小屏小的字体大小以及单行公式超长会有横向滚动条，看看ok吗

**Comment by clatisus** [comment]
ok了，非常完美，多谢
