### ISSUE TITLE
鼠标滚轮滚动TOC时，滚动到底部后又跳回顶部，体验不好。

### ISSUE THREAD

**Issue by weiyf** [yscoder/hexo-theme-indigo#121]
鼠标滚轮滚动TOC时，滚动到底部后又跳回顶部，体验不好。
鼠标在TOC区域滚动滚轮，TOC到达底部之后应该继续滚动正文。

**Comment by yscoder** [comment]
The d365fa2 fix it.

**Comment by weiyf** [comment]
更新后发现滚动文章TOC没有跟着改变当前标题， 而且打开侧边栏会导致TOC压缩

**Comment by yscoder** [comment]
不明白你的意思，来个链接

**Comment by yscoder** [comment]
愚蠢的错误，我明白了

**Comment by weiyf** [comment]
[链接](http://weiyf.cn/2016/10/31/DataBinding%E2%80%94%E2%80%94data-binding-guide/)
滚动文章时，TOC一直停留在第一项，打开侧边栏，TOC被压缩，之前是整体右移， 点击TOC中间标题更明显

**Comment by yscoder** [comment]
> TOC被压缩

是什么意思？

**Comment by weiyf** [comment]
我发现只有小屏幕才会看出效果，稍等， 我录制个gif

**Comment by weiyf** [comment]
发现在ubuntu录制gif很麻烦，又切回Windows10了，心累
![demo](https://cloud.githubusercontent.com/assets/12067656/20549591/cff78b0a-b168-11e6-8b89-851d717d417c.gif)
