### ISSUE TITLE
new draft时，建立的tag，为正式发布到post的文章中的tag会在tag页面显示，但并未生成此页面，点击后会出错，估计categories也是如此。

### ISSUE THREAD

**Issue by weiyf** [yscoder/hexo-theme-indigo#122]
new draft时，建立的tag，为正式发布到post的文章中的tag会在tag页面显示，但并未生成此页面，点击后会出错，估计categories也是如此。

**Comment by yscoder** [comment]
第一次 new draft，没有发现这样的情况

**Comment by weiyf** [comment]
new draft之后， 在new出来的draft中的tag[]填写tag，例如tag[aaaa, bbbbb]， hexo s之后在TAG页面会生成aaaa和bbbb
![image](https://cloud.githubusercontent.com/assets/12067656/20206766/b803f406-a81d-11e6-93f6-96e48a3e2584.png)

![image](https://cloud.githubusercontent.com/assets/12067656/20206795/dddba016-a81d-11e6-8741-5c8ea22c42fb.png)

![image](https://cloud.githubusercontent.com/assets/12067656/20206802/ef2ad81e-a81d-11e6-9866-af6f7c7cccc7.png)

**Comment by yscoder** [comment]
是只有 tags 页有 draft 中的 tag，还是其他子页面也有？

**Comment by weiyf** [comment]
目前只发现tag页有
