### ISSUE TITLE
分享文章链接的时候默认使用了avtar头像

### ISSUE THREAD

**Issue by Chanran** [yscoder/hexo-theme-indigo#123]
分享文章链接的时候默认使用了avtar头像而不是文章里第一张图片

**Comment by yscoder** [comment]
现在可以通过在 Markdown 元数据中指定 `photos` 设置分享的默认图片。

```md
---
title: title
date: 2016-11-20 19:54:28
photos: ['http://placekitten.com/500/500']
---
```

这次顺便重写了分享的实现。

**Comment by Chanran** [comment]
@yscoder 发现分享文章还是出问题了。
[写nodejs遇到的坑](https://chanran.github.io/2016/11/29/%E5%86%99nodejs%E6%97%B6%E9%81%87%E5%88%B0%E7%9A%84%E5%9D%91/)

![image](https://cloud.githubusercontent.com/assets/11496220/20710375/23191126-b675-11e6-8b37-8ee29f0012e3.png)

**Comment by yscoder** [comment]
没看出来是什么问题

**Comment by Chanran** [comment]
@yscoder 。。。分享到的时候还是使用了avtar头像而不是我在代码里加的photos[0]。

**Comment by yscoder** [comment]
![image](https://cloud.githubusercontent.com/assets/12295378/20711281/d9a4573a-b679-11e6-877b-fa81b34f81c9.png)

**Comment by Chanran** [comment]
微信试一下？

**Comment by yscoder** [comment]
微信是二维码

**Comment by Chanran** [comment]
二维码会出问题吗？

**Comment by yscoder** [comment]
微信没有开放的分享接口，目前所有的实现都是把页面链接转成二维码，然后微信扫描打开网页。

**Comment by Chanran** [comment]
好，谢谢了。
