### ISSUE TITLE
关于部分含日文标题进不去的奇葩问题

### ISSUE THREAD

**Issue by yuangezhizao** [yscoder/hexo-theme-indigo#124]
很奇葩的问题，本地`hexo s`预览无任何问题。
然而`hexo d`上去之后在首页能看见，
![qq20161112-0](https://cloud.githubusercontent.com/assets/16861681/20237035/2733fc1a-a902-11e6-801e-fcbd284bb5d1.png)
点`阅读全文`进去就报`404`了。
![qq20161112-1](https://cloud.githubusercontent.com/assets/16861681/20237054/afa96b16-a902-11e6-9705-f7d8542e7d78.png)
`https://blog.yuangezhizao.cn/2016/Music/田村大魔王教你洗脑 - めてお☆いんぱくと`，只有这个链接进去才好使，可这个链接就是`阅读原文`的链接啊！难道是日文编码的问题？
附：
1. 应该并不是因为标题含空格的原因；
2. 从`404`页面手动复制出来的链接地址为：`https://blog.yuangezhizao.cn/2016/Music/%E7%94%B0%E6%9D%91%E5%A4%A7%E9%AD%94%E7%8E%8B%E6%95%99%E4%BD%A0%E6%B4%97%E8%84%91%20-%20%E3%82%81%E3%81%A6%E3%81%8A%E2%98%86%E3%81%84%E3%82%93%E3%81%AF%E3%82%9A%E3%81%8F%E3%81%A8/`；
3. 我的博客地址：[https://blog.yuangezhizao.cn](https://blog.yuangezhizao.cn)。

**Comment by yscoder** [comment]
![image](https://cloud.githubusercontent.com/assets/12295378/20237284/82807980-a908-11e6-813f-bd47f31d0272.png)

一个正常显示的 url 和 404 的 url 居然是不同的编码。

建议把 md 文件名和页面标题区分开，文件名只用字母、数字、连接符，能避免这些问题。

![image](https://cloud.githubusercontent.com/assets/12295378/20237335/df030514-a909-11e6-8343-f1ee7e706ef1.png)

**Comment by yscoder** [comment]
或者你改下 `permalink` 设置，以 `.html` 结尾试试

**Comment by yuangezhizao** [comment]
#### 1. 尝试把`permalink`从`:year/:title/`改至`:year/:title.html`，无果；
#### 2. 目前解决方法：把`.md`文件名改至`递增数字`，即：![qq20161112-2](https://cloud.githubusercontent.com/assets/16861681/20237702/00dd3e06-a915-11e6-96a7-3876026e3cae.png)
#### 感谢帮助
