### ISSUE TITLE
git clone 的时候碰到的问题。

### ISSUE THREAD

**Issue by arronf2e** [yscoder/hexo-theme-indigo#125]
fatal: Not a git repository (or any of the parent directories): .git

请问如何解决，git init?

**Comment by yscoder** [comment]
你的当前目录应该已经是一个 git repo 了。
如果是不重要的仓库，把显示隐藏文件打开，删除 .git 目录。
或者直接以下载的方式安装，https://github.com/yscoder/hexo-theme-indigo/archive/card.zip
