### ISSUE TITLE
头像配置怎么无效

### ISSUE THREAD

**Issue by 471448446** [yscoder/hexo-theme-indigo#126]
avatar: /img/logo.jpg
没有效果

**Comment by 471448446** [comment]
确实是添加了，可是现实不出来。

**Comment by yscoder** [comment]
浏览器控制台有什么错误？

**Comment by 471448446** [comment]
怎么看？

**Comment by yscoder** [comment]
F12，点开 `console` 面板

**Comment by 471448446** [comment]
http://localhost:4000/img/config_head.jpg 404 (Not Found)
但是我在img下已经添加了
配置：
#你的头像url
avatar: /img/config_head.jpg

**Comment by 471448446** [comment]
#你的头像url
avatar: //placekitten.com/200/200
用默认的可以

**Comment by yscoder** [comment]
在确认下资源管理器显示的路径是 `hexo\themes\indigo\source\img` 吗？

**Comment by 471448446** [comment]
![image](https://cloud.githubusercontent.com/assets/7636279/20415573/2535817e-ad74-11e6-8973-ff98c64207c5.png)
![image](https://cloud.githubusercontent.com/assets/7636279/20415582/36562152-ad74-11e6-9726-4a3b52e84463.png)
确定

**Comment by yscoder** [comment]
站点是生成到子目录中了吗？

**Comment by 471448446** [comment]
![image](https://cloud.githubusercontent.com/assets/7636279/20415732/3324f322-ad75-11e6-92ae-f545518b716f.png)
这里面也有这个文件，

**Comment by yscoder** [comment]
控制台能报出 404，说明配置没有问题、页面存在图片引用，`hexo clean` 清下缓存试试。

**Comment by 471448446** [comment]
..
每次布置都是
clean
g
s

**Comment by 471448446** [comment]
![image](https://cloud.githubusercontent.com/assets/7636279/20415960/b071aa72-ad76-11e6-8414-d0386b4e2ffb.png)
站点图标前面有个/lymyBetter 而头像没有是不是这个原因？
我在浏览器打开http://localhost:4000/img/config_head.jpg  404
打开：http://localhost:4000/lysmBetter/img/config_head.jpg 可以

**Comment by yscoder** [comment]
你的站点是放到子目录中了，看看 `hexo/config.yml` 中的 `url` 和 `root` 配置。
这里你加上目录前缀就可以了。

**Comment by yscoder** [comment]
这个我应该 `fix`。

**Comment by 471448446** [comment]
我是准备放到github的pages上所以root 后面需要更上repo的名字像这样 `root: /lysmBetter`，这样才用得起。不然主题的css样式完全没有效果。

**Comment by yscoder** [comment]
你的配置不用改了。

**Comment by 471448446** [comment]
可以了 谢谢
