### ISSUE TITLE
搜索功能异常

### ISSUE THREAD

**Issue by zema1** [yscoder/hexo-theme-indigo#127]
我按照官方的方法安装hexo 并生成blog,然后安装主题， 安装依赖所有的都正常，但搜索只能搜索标题和日期等，无法搜索全文，我并未配置hexo-json-content插件(默认有全文), 查看生成的content.json 是有内容的。

**Comment by yscoder** [comment]
有没有在线链接？

**Comment by zema1** [comment]
没， 刚从typecho 转过来。。 我用hexo server -l 可以发现content.json确实被请求了,但就是不解析内容，输title却是可以的。这是我电脑的信息
hexo -V

```
hexo: 3.2.2
hexo-cli: 1.0.2
os: Darwin 15.6.0 darwin x64
http_parser: 2.7.0
node: 6.3.1
v8: 5.0.71.57
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
```

**Comment by zema1** [comment]
我刚发现一个问题，在我这里生成的content.json文件没有text字段，无论在配置文件中设置true还是false 都没有，而是一直有content字段，是不是和这个有关？

**Comment by yscoder** [comment]
嗯，搜索检索的是 text 字段，因为 content 字段含有 html 标签。

**Comment by zema1** [comment]
知道原因了，跟主题无关，是那个json插件的问题，几天前他更新了3.0版本，用这个版本有问题，退回2.x版本就正常了。

**Comment by yscoder** [comment]
去看了下代码变更，作者用 ES6 重写了。
作者可能粗心了，把字段名写错了，导致 `text` 字段没有生成。
我已经向他提交 PR 了。

**Comment by zema1** [comment]
Great! Thinks very much for your effects.😋

**Comment by yf-web** [comment]
那我们该如何解决这个问题呢？把hexo回退到老版本吗？有没有其他解决办法，还是等hexo的新版？谢谢！

**Comment by yscoder** [comment]
跟 Hexo 无关，是 `json-content` 插件的问题，你可以回退这个插件或者等我的 PR 合并后在更新插件。

回退旧版本：

```
npm i -S hexo-generator-json-content@2.1.3
```

**Comment by yscoder** [comment]
作者已合并 PR，最新版本为 3.01。
