### ISSUE TITLE
能否添加一下点击文章图片放大的功能？

### ISSUE THREAD

**Issue by weiyf** [yscoder/hexo-theme-indigo#129]
能否添加一下点击文章图片放大的功能？

**Comment by xdcxdc** [comment]
希望增加图片的 title 居中显示在图片下方。

**Comment by yscoder** [comment]
@xdcxdc Markdown 语法是不支持的，只能写扩展了。

**Comment by xdcxdc** [comment]
应该是可以的吧 
如： https://cntchen.github.io/2016/05/09/%E5%9B%BD%E5%86%85%E4%B8%BB%E8%A6%81%E5%9C%B0%E5%9B%BE%E7%93%A6%E7%89%87%E5%9D%90%E6%A0%87%E7%B3%BB%E5%AE%9A%E4%B9%89%E5%8F%8A%E8%AE%A1%E7%AE%97%E5%8E%9F%E7%90%86/

另外， Mardown 里面图片标签有title的啊
 `![图片替代文字](https://i.xdc.at/assets/avatar/avatar.png "图片标题")`
![图片替代文字](https://i.xdc.at/assets/avatar/avatar.png "图片标题")

**Comment by yscoder** [comment]
这个是在前端处理过的，把 `img` 的 `title` 属性拿出来，创建 DOM。

**Comment by yscoder** [comment]
使用标签插件创建下方显示标题的图片。

```
{% image [url] [title] %}
```

**Comment by Wegome** [comment]
文章 md 内容下使用
{% image [https://ws3.sinaimg.cn/mw690/8bf740e1gw1f72nglj227j21hc0xctl2.jpg] [小雪] %}

{% image [https://camo.githubusercontent.com/27f93154ebf09d1c18d4cbf804c8781bf871fdae/68747470733a2f2f692e7864632e61742f6173736574732f6176617461722f6176617461722e706e67] [测试] %}

 试了几次，得到的是
![fireshot capture 9 - i - - http___localhost_4000_spark-3673 html](https://cloud.githubusercontent.com/assets/6015834/20620456/c8a0a12a-b334-11e6-9238-fb8128e3588e.png)

是用错了吗？

**Comment by yscoder** [comment]
不需要加中括号...

**Comment by Wegome** [comment]
知道了。谢谢。。。。

**Comment by yscoder** [comment]
[Update log](https://github.com/yscoder/hexo-theme-indigo/releases/tag/v1.3-card)
