### ISSUE TITLE
目录长的情况下显示不全

### ISSUE THREAD

**Issue by ArtisanM** [yscoder/hexo-theme-indigo#13]
如下，博客右侧的目录太长的话，后面的目录就看不到了。而且目录还盖住了评论区
[blog](http://duanmo.me/2016/04/17/memory%20leak%20summary/)

**Comment by yscoder** [comment]
现在目录超过一屏后会有滚动机制，你还需要修改下友言的文档位置，放到`class="post-main"`这个块内。
