### ISSUE TITLE
提交给github出错

### ISSUE THREAD

**Issue by MRwangqi** [yscoder/hexo-theme-indigo#130]
我在blog的_config.xml里面，最后添加了
deploy:
  type: git
  repository: https://github.com/MRwangqi/MRwangqi.github.io
  branch: master

这段话，只要添加这段话，连本地的服务都启动不起来，报错，求解啊

**Comment by MRwangqi** [comment]
我晓得了，格式错误了，应该是下面的格式
deploy:
   type: git
   repository: https://github.com/MRwangqi/MRwangqi.github.io
   branch: master

**Comment by yscoder** [comment]
两个格式好像没有区别。

**Comment by MRwangqi** [comment]
deploy:
     type: git
     repository: https://github.com/MRwangqi/MRwangqi.github.io
     branch: master

**Comment by MRwangqi** [comment]
deploy:
空格空格type: git
空格空格repository: https://github.com/MRwangqi/MRwangqi.github.io
空格空格branch: master

前面是有两个空格，回复手动打空格没用

**Comment by yscoder** [comment]
...好吧，你应该用 markdown 排版。
