### ISSUE TITLE
可否不显示未定义

### ISSUE THREAD

**Issue by NoahDragon** [yscoder/hexo-theme-indigo#133]
如果没有定义图片名称，会在图片下方显示未定义：
![image](https://cloud.githubusercontent.com/assets/5704064/20636366/c34ce9b8-b339-11e6-80bd-4157d6488c41.png)

能否让这个不显示，或者有个设置，可以不显示图片名称？

**Comment by NoahDragon** [comment]
顺带一提，新加的plugin.js需要node 6以上方可运行。

**Comment by yscoder** [comment]
你是这样插入图片的吗？

```
![](/image-link.jpg)
```

**Comment by NoahDragon** [comment]
是的

**Comment by yscoder** [comment]
fix
