### ISSUE TITLE
chrome下阅读文章时右侧导航栏bug

### ISSUE THREAD

**Issue by B-sirius** [yscoder/hexo-theme-indigo#135]
chrome下，在阅读文章界面缩放网页后，点击快速导航栏会出现非常喜感的bug，在firefox，edge下测试均没有问题。顺便发现在ie11下快速导航栏压根没用啊......不是说兼容ie10+么

ps：测试界面是您的博客
![bug_indigo](https://cloud.githubusercontent.com/assets/15071193/20669429/27dc2d4a-b5af-11e6-8c1e-a141ee718723.gif)

**Comment by zema1** [comment]
我想说 我用Chrome ，使用TOC也会类似的情况，跳的很快，只能刷新页面才行。。我一直以为是我的问题。。之前是没问题的，不知道哪次更新就这样了。。

**Comment by yscoder** [comment]
缩放的问题，没有考虑到。屏幕缩放后，高度发生变化，会导致计算出错。

**Comment by yscoder** [comment]
fix
