### ISSUE TITLE
功能改进建议

### ISSUE THREAD

**Issue by zema1** [yscoder/hexo-theme-indigo#136]
1. 我使用disqus评论，由于众所周知的原因，disqus往往无法正常访问，但能否将disqus评论改成异步加载方式，即使评论加载不出来，页面也该是已经加载好的，现在的情况是页面载入卡在了disqus的js载入上,比较影响体验。

2. 推荐将qrcode的API换成这个[http://goqr.me/api/](http://goqr.me/api/), 简单好用，我自己改成这个了。主要是支持HTTPS。。

辛苦了

**Comment by yscoder** [comment]
这个 API 没有墙吧？

**Comment by zema1** [comment]
没有，可以看下我的博客 [www.uihere.com](https://www.uihere.com)

**Comment by yscoder** [comment]
disqus 本来就是异步的...

**Comment by zema1** [comment]
但为啥我这一直得等他加载完js 页面才能显示出来... 我改了一东西，但没碰过js，应该不会影响吧。。

**Comment by yscoder** [comment]
应该改成延迟加载

**Comment by zema1** [comment]
恩恩 期待下个版本带来优化

**Comment by yscoder** [comment]
你试试现在 disqus 还会不会卡住，已经放到页面加载完成后载入了。
有些脚本内部会使用页面加载事件执行代码，此类脚本不能延迟到页面加载完成后，比如多说。

**Comment by zema1** [comment]
可以了，正是我需要的，非常感谢，可以close这个issue了
