### ISSUE TITLE
新增功能建议

### ISSUE THREAD

**Issue by cstsinghua** [yscoder/hexo-theme-indigo#139]
1.能不能在每篇文章里面引入“创建时间”、“最后修改时间”两个值，在每篇文章标题下面或者其他位置能看到；
2.能不能加入访问量统计的功能，这样在每篇文章里面可以看到该篇文章被点击或者访问了多少次；

**Comment by yuangezhizao** [comment]
其实第一个问题我也想问，第二个问题可以用不蒜子

**Comment by yscoder** [comment]
@yuangezhizao 可以来个 不蒜子 的 PR

**Comment by yscoder** [comment]
#141
