### ISSUE TITLE
小建议

### ISSUE THREAD

**Issue by yuangezhizao** [yscoder/hexo-theme-indigo#145]
最近看了一些人的博客……
1. 现有“跳至顶部”的按钮，是否方便增加“跳至底部”和“跳至评论”的按钮（将其三竖着一起放置在右侧）？

**Comment by weiyf** [comment]
跳至底部是有什么作用呢？跳到评论可以点击评论数

**Comment by yuangezhizao** [comment]
最近看了一些人的博客……
2. 将左侧菜单移至顶侧如何？

**Comment by yuangezhizao** [comment]
3. 文章分页改为滚到底部自动加载下一页内容如何，类似于手机QQ空间的加载？

**Comment by yuangezhizao** [comment]
4.  增加在博文内容页，按键盘左右键博文跳转到上一篇和下一篇的功能如何？

**Comment by weiyf** [comment]
@yuangezhizao 这个主题是Material Design风格的主题，建议了解一下Material Design风格[Material Design](https://material.google.com/#introduction-principles)

**Comment by yuangezhizao** [comment]
@weiyf OK
