### ISSUE TITLE
有http的内容会自动变成链接，这个可不可以不自动转换

### ISSUE THREAD

**Issue by MJPiero** [yscoder/hexo-theme-indigo#148]
有http的内容会自动变成链接，这个可不可以不自动转换。

**Comment by yscoder** [comment]
不明白你的意思，是什么场景？

**Comment by MJPiero** [comment]
就比如我想在文档里面写个示例 "url": "https://package/path" 比如就这个文本，然后编译之后，会自动把https://package/path 转换成可点击跳转的链接

**Comment by yscoder** [comment]
这是 Markdown 的锅，github 里也是一样。你可以用行内代码格式包裹避免生成链接。

```md
`https://package/path`
```
生成

`https://package/path`

**Comment by MJPiero** [comment]
嗯嗯，后来我是这么弄了，谢谢。
