### ISSUE TITLE
关于文章内&外图片显示的问题

### ISSUE THREAD

**Issue by yuangezhizao** [yscoder/hexo-theme-indigo#151]
#### 文章内的图片貌似被强制放大到最大：
![default](https://cloud.githubusercontent.com/assets/16861681/21054721/ae37353e-be69-11e6-9ec7-d41227657328.jpg)
#### 点击放大后才是原本的大小：
![default](https://cloud.githubusercontent.com/assets/16861681/21054755/d8711e96-be69-11e6-9fd8-76d7f2031941.jpg)
#### 同样也出现在这种页面（可以看到超出了引用线）：
![qq 20161209235332](https://cloud.githubusercontent.com/assets/16861681/21055059/ec866890-be6a-11e6-827e-a1fbb6bc2d8f.jpg)

**Comment by yscoder** [comment]
图片原始尺寸太大，会被等比缩放。在页面中最大宽度960，无高度限制，所以尺寸最大为960 x 960。全屏模式下，最大高度为浏览器窗口高度 - 上下边距 = 862，所以缩放后为 862x862，显得变小了。

![image](https://cloud.githubusercontent.com/assets/12295378/21070130/d41f352e-bebb-11e6-855d-0d6cbb9b0721.png)

越界的问题，我改下

**Comment by yuangezhizao** [comment]
我发的最后一张图片里出现的图片跨越了引用线的问题可否修复下？

**Comment by yuangezhizao** [comment]
感谢修复

**Comment by Wegome** [comment]
@yscoder 
markdown如下
![大雪](https://ws1.sinaimg.cn/mw690/8bf740e1gw1f72nh3tcgoj21hc0xc4qp.jpg)

出现的问题：
图片象数小于你设定的大小时，鼠标悬停时，不会显示放大镜图标，这个没问题。但是，原来在图片下显示图片名称，如 大雪，现在好像不显示了。
图片象数大于设定值时，鼠标悬停会显示放大镜图标，图片下会显示图片名称。

能否小图片也显示名称？

**Comment by yscoder** [comment]
@Wegome 链接

**Comment by Wegome** [comment]
@yscoder
图片我放到一起了
http://www.zhinuo.space/spark/9087.html

**Comment by yscoder** [comment]
@Wegome 第一张图片你是怎么插入的，是markdown语法吗？

**Comment by Wegome** [comment]
@yscoder 
是的
![大雪](https://ws1.sinaimg.cn/mw690/8bf740e1gw1f72nh3tcgoj21hc0xc4qp.jpg)  
![2](https://ws3.sinaimg.cn/mw690/8bf740e1jw1f7itko2alrj21hc0xc12f.jpg)
![3](https://ws2.sinaimg.cn/mw690/8bf740e1jw1f7itkru196j21hc0xc7ce.jpg)

**Comment by Wegome** [comment]
@yscoder 
是的
![大雪](h ttps://ws1.sinaimg.cn/mw690/8bf740e1gw1f72nh3tcgoj21hc0xc4qp.jpg)  
![2](h ttps://ws3.sinaimg.cn/mw690/8bf740e1jw1f7itko2alrj21hc0xc12f.jpg)
![3](h ttps://ws2.sinaimg.cn/mw690/8bf740e1jw1f7itkru196j21hc0xc7ce.jpg)

**Comment by yscoder** [comment]
我这里测试的没问题。

```md
# test

![大雪](https://ws1.sinaimg.cn/mw690/8bf740e1gw1f72nh3tcgoj21hc0xc4qp.jpg) 
![2](https://ws3.sinaimg.cn/mw690/8bf740e1jw1f7itko2alrj21hc0xc12f.jpg)
![3](https://ws2.sinaimg.cn/mw690/8bf740e1jw1f7itkru196j21hc0xc7ce.jpg)
```

![image](https://cloud.githubusercontent.com/assets/12295378/21072759/493dbe24-bf08-11e6-9ce8-ab4776c3b9c0.png)

**Comment by Wegome** [comment]
@yscoder 
奇怪。
谢谢了。我再找找原因。
