### ISSUE TITLE
手机端搜索框颜色

### ISSUE THREAD

**Issue by Imfan** [yscoder/hexo-theme-indigo#160]
在手机上搜索关键字后，关键字看不到，可能是被覆盖，或者颜色有问题，我没弄明白

**Comment by yscoder** [comment]
不是白色吗？

**Comment by Imfan** [comment]
![image](https://cloud.githubusercontent.com/assets/23480021/21877649/6e32b60c-d8c7-11e6-93cc-902953062126.png)
是白色，这是搜索之后显示的界面，看不到被搜索的关键字

**Comment by yscoder** [comment]
看起来是 IOS QQ 内置浏览器，回头我看一下

**Comment by Imfan** [comment]
恩恩，是的，我的手机浏览器访问也是这样！谢谢你O(∩_∩)O

**Comment by yscoder** [comment]
OK了
