### ISSUE TITLE
404配置不成功

### ISSUE THREAD

**Issue by Wensibob** [yscoder/hexo-theme-indigo#161]
按照教程，404的路径配置路径为：blog/source/404.html，
404.html的内容为：
```html
layout: false    
title: "温斯渤 | 404"
---
```
这是[我的博客](http://www.wensibo.top "_blank")请问如何解决，谢谢。

**Comment by yscoder** [comment]
http://www.wensibo.top/404.html  页面没问题，应该跟你的 WEB 服务器 404 配置有关。
