### ISSUE TITLE
文章详情页面中，用于展示文章内容的卡片可以设置大小吗

### ISSUE THREAD

**Issue by Wensibob** [yscoder/hexo-theme-indigo#165]
文章详情页面中，用于展示文章内容的卡片感觉有点小，尤其是插入代码时，当代码的一行款都比较长的时候就不是很好看，请问可以设置宽度吗？
![文章详情页面](https://github.com/Wensibob/README/blob/master/img/2017-01-24T06-57-04.037Z.png?raw=true)

**Comment by jasonzhang1986** [comment]
我也觉得有点窄, @Wensibob 你有办法了吗？

**Comment by Wensibob** [comment]
我目前还是没有解决方法，你可以看一下我的[网站](http://www.wensibo.top) @edgarCode

**Comment by yscoder** [comment]
增加了新的的 less 变量，修改 `source/css/_partial/variable.less` 21行中的值。

**Comment by Wensibob** [comment]
@yscoder 关于这个宽度的设置，我有一个建议，如果将宽度单位设置为px那么不管在普通的14寸电脑屏幕还是在25寸的显示器上显示，宽度都是一样宽的，可不可以考虑一下根据不同的屏幕大小动态改变这个宽度呢？像下面这样：
```
@media (max-width: 980px) {
  .facet_sidebar {
    display: none;
  }
}
```
