### ISSUE TITLE
评论无法显示

### ISSUE THREAD

**Issue by mikaelzero** [yscoder/hexo-theme-indigo#166]
本地调试的时候是有显示的  但是部署到github上的时候，就不显示了，多说的名字那些验证过是对应的

**Comment by yuangezhizao** [comment]
F12打开看看有没有报错

**Comment by mikaelzero** [comment]
只有一个关于统计的警告  没有报错

**Comment by yscoder** [comment]
链接发一下

**Comment by mikaelzero** [comment]
https://miaoyongjun.github.io/

**Comment by yscoder** [comment]
我这里打开是正常的。

![image](https://cloud.githubusercontent.com/assets/12295378/22871819/90589abc-f1ef-11e6-892c-a47130decb9b.png)

**Comment by mikaelzero** [comment]
这就奇怪了  你用手机访问看看有没有  我手机喝家里的电脑访问是没有的  公司的电脑访问是有的

**Comment by yscoder** [comment]
手机也没问题，应该是你家里的网络有问题。
