### ISSUE TITLE
你好，想提2个想法

### ISSUE THREAD

**Issue by lepig** [yscoder/hexo-theme-indigo#167]
1. 进入文章详情页的时候，希望可以在右上角(分享图标后面)加一个主页链接,这样当我看完一篇文章的时候就可以直接返回到主页。虽然左上角那个也可以，但是需要2步操作，感觉不太好

2. 详情页的页面显示宽度能否配置一个选项用于自定义显示宽高。之前用过`Next主题`,它有一个这个宽度的选项。感觉在大屏上两侧的留空太大，而且有个问题是对于一些有贴代码的，稍微一长一点就要拖动那个水平滚动条，很麻烦

在说一句，主题很Nice

**Comment by yscoder** [comment]
1. ~~为什么返回主页在左上角会多一步？左上角和右上角有什么区别？~~
2. 与 #165 需求一致

**Comment by yuangezhizao** [comment]
1. 关闭大屏幕模式就不会多一步 @lepigs

**Comment by yscoder** [comment]
@lepigs  刚才我没理解过来左上角是菜单按钮。
放到右上角有点不太合适，我考虑一下吧。

**Comment by lepig** [comment]
@yscoder 你好,对于第一个问题我今天多熟悉了下主题,发现可以直接点击详情页下面的作者头像跳转到首页,所以可以无视我的问题.谢谢了
