### ISSUE TITLE
反馈2个问题

### ISSUE THREAD

**Issue by ghost** [yscoder/hexo-theme-indigo#168]
1、在Wiki页面中，git clone地址有写错造成无法clone：
https://github.com/yscoder/hexo-theme-indigo/wiki/%E5%AE%89%E8%A3%85

2、多说评论只有一条的情况下点击删除，会显示-1条评论

感谢作者制作这款Theme。

**Comment by lepig** [comment]
借楼反馈一下
![bug](https://cloud.githubusercontent.com/assets/5689279/22874995/1b61a662-f204-11e6-8f5c-a5f050c95a7f.jpg)
 Chrome56

**--2017-2-13 17:05更新--**
书写完评论点击"发表评论"以后出出现这样,如果重新刷新以后,就正常了.

**Comment by yscoder** [comment]
@leave01 

1. 地址没有问题。
![image](https://cloud.githubusercontent.com/assets/12295378/22876990/400c8fc2-f20e-11e6-9b47-f89dc3c3ecb5.png)
2. 这种问题应该是多说的锅，不过我测试后也没发现该问题。

**Comment by yscoder** [comment]
@lepigs 

新评论多说脚本会添加一个行内样式 `overflow: hidden`，把显示内容截断了。。。刷新下就正常了。
这个问题下次更新时解决。
