### ISSUE TITLE
sometimes aside menu padding not disappear

### ISSUE THREAD

**Issue by gracefullight** [yscoder/hexo-theme-indigo#171]
Hi yscoder

v. 1.4.2
![image](https://cloud.githubusercontent.com/assets/11773683/23196030/54ed5c80-f8fa-11e6-8abd-6427f6ccf3fa.png)

**#menu.hide+#main {
    padding-left: 0;
}**

Somtimes, that css attribute is missing.
So the content layout moves.

**Comment by yscoder** [comment]
Can you change the position of the element `class="adsbygoogle"` in the document?

**Example:**

``` html
<!-- new position -->
<ins class="adsbygoogle">...</ins>
<aside id="menu" class="hide">...</aside>
<!-- old position -->
<!-- <ins class="adsbygoogle">...</ins> -->
<main id="main">...</main>
```

**Comment by gracefullight** [comment]
![image](https://cloud.githubusercontent.com/assets/11773683/23197239/3ac3c21a-f902-11e6-9b83-b03539158ffe.png)

I can not change it because it's not the code I added.
I think it's added from page-level ads, should I remove it?

currently using the following script temporarily:
``` js script.ejs
document.addEventListener("DOMContentLoaded", function(event) {
    if(document.querySelector('#menu').classList.contains('hide')){
    	document.querySelector('#main').style.paddingLeft = 0;
    }
});
```

**Comment by yscoder** [comment]
Modify [layout.less#L30](https://github.com/yscoder/hexo-theme-indigo/blob/card/source/css/_partial/layout.less#L30)

``` css
/* before */
+ #main {
    padding-left: 0;
}
```

``` css
/* after */
~ #main {
    padding-left: 0;
}
```

Replace the adjacent selector with the sibling selector.

**Comment by gracefullight** [comment]
It works, thanks!
