### ISSUE TITLE
https下有js报错

### ISSUE THREAD

**Issue by yuangezhizao** [yscoder/hexo-theme-indigo#177]
部署在`coding.net`平台，`http`访问`Console`无任何报错，`https`访问如图。想知道问题出在哪里。
![qq 20170311100443](https://cloud.githubusercontent.com/assets/16861681/23819504/35c2def2-0642-11e7-8aac-8dda734ea793.jpg)

**Comment by yuangezhizao** [comment]
补充：同样地部署在自己服务器上（https）就没有报错，难道是`coding.net`的问题，很奇怪？

**Comment by yscoder** [comment]
我去你博客没看到这个错误，现在好了？

**Comment by yuangezhizao** [comment]
才发现，确实好了……
