### ISSUE TITLE
首页文章列表，能否设置图片

### ISSUE THREAD

**Issue by mmmwhy** [yscoder/hexo-theme-indigo#178]
https://blog.viosey.com/

就像这个样子，文章可以设置  thumbnail	缩略图地址

**Comment by CoderLengary** [comment]
请问有解决的办法么。。这几天为了给摘要弄个图片弄到要跪。。。

**Comment by hellokaton** [comment]
同希望有这个功能。

如果 `大标题` 的背景色可以换成自定义图片就更好了，我试了下，`top-header` 也是一样的颜色，这就尴尬了 😓

**Comment by Phoenix-Ann** [comment]
同求~！https://haojen.github.io/Claudia-theme-blog/

**Comment by Guidozijef** [comment]
我加上了，
https://guidozijef.github.io/

**Comment by lanxuewei** [comment]
同问，现在有这功能吗？

**Comment by Guidozijef** [comment]
我把他这个改成可以加图片的了，www.zijef.pw------------------ 原始邮件 ------------------
发件人: "蓝学伟"<notifications@github.com>
发送时间: 2019年6月5日(星期三) 下午3:50
收件人: "yscoder/hexo-theme-indigo"<hexo-theme-indigo@noreply.github.com>;
抄送: "Guidozijef"<913497146@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [yscoder/hexo-theme-indigo] 首页文章列表，能否设置图片 (#178)



同问，现在有这功能吗？
 
&mdash;

**Comment by lanxuewei** [comment]
@Guidozijef 你这个模板都不一样把，你这个模板确实是列表可以展示图片的，我们使用的是 hexo-theme-indigo 主题的

**Comment by Guidozijef** [comment]
是一个模板，我把代码改了的，我刚开始跟你妈一样的，其他东西都是我加的------------------ 原始邮件 ------------------
发件人: "蓝学伟"<notifications@github.com>
发送时间: 2019年6月5日(星期三) 下午4:46
收件人: "yscoder/hexo-theme-indigo"<hexo-theme-indigo@noreply.github.com>;
抄送: "Guidozijef"<913497146@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [yscoder/hexo-theme-indigo] 首页文章列表，能否设置图片 (#178)



@Guidozijef 你这个模板都不一样把，你这个模板确实是列表可以展示图片的，我们使用的是 hexo-theme-indigo 主题的
 
&mdash;
