### ISSUE TITLE
反馈iOS和Mac下的2个问题，希望能关注一下

### ISSUE THREAD

**Issue by hewz** [yscoder/hexo-theme-indigo#18]
1.测试环境iOS9.3.1，Safari直接打开没问题，微信微博等应用浏览会闪退，并且界面跳回主页。
2.Mac(10.11.4) Chrome(v49)不显示menu中 github的图标，其它浏览器正常。

同这个issue追加内容， https://github.com/yscoder/hexo-theme-indigo/issues/5

**Comment by yscoder** [comment]
问题1我修复过了，我是在ipad上修复的，你可以访问 [我的博客](http://imys.net) 测试现在是否正常再 pull 获取更新。如果还有问题，望继续反馈。

问题2我这边没有发现这种情况，以下问题可能导致出现这种情况，你可以逐一排查：

1. 菜单项配置是否正确
2. 是否更改过`header.ejs`
3. 是否更改过`fontawesome.less`

**Comment by hewz** [comment]
OK，感谢~

**Comment by yscoder** [comment]
关于图标不显示的问题，找到答案了。是因为 Adblock 。同 #26
