### ISSUE TITLE
样式丢失

### ISSUE THREAD

**Issue by hui46226021** [yscoder/hexo-theme-indigo#181]
请问 为什么 我在本地 没问题  上传到github上样式就乱了

**Comment by yuangezhizao** [comment]
F12 看看有没有报错

**Comment by hui46226021** [comment]
F12 CSS 都加载到了 也没有报错 

不过 我安装主题的时候 是不是又问题  
我 git clone git@github.com:yscoder/hexo-theme-indigo.git themes/indigo  提示我 没有权限

我就down下了你的代码  然后 把card 那个文件夹 扔到了跟目录的 theme 文件夹下面，
然后theme： card
这么弄得 会不会是这的问题

**Comment by yscoder** [comment]
把站点链接发一下

**Comment by hui46226021** [comment]
https://hui46226021.github.io/   多谢

**Comment by yscoder** [comment]
本地缓存没更新，样式应该是你上个主题的。

执行：
```
hexo clean
hexo d -g
```
