### ISSUE TITLE
#165的问题在本地测试之后可以得到改善，但是部署在服务器上并没有见效

### ISSUE THREAD

**Issue by Wensibob** [yscoder/hexo-theme-indigo#182]
#165的问题——即内容页面过窄的问题在本地 `hexo s`之后可以得到改善，但是部署到服务器的时候，[没有效果](http://wensibo.top)，不知道是不是只是复制了public文件夹的原因？ @yscoder

**Comment by yscoder** [comment]
静态资源更新（css, js等），需要清除 Hexo 缓存 `hexo clean` 再生成。

**Comment by Wensibob** [comment]
已成功解决，谢谢
