### ISSUE TITLE
使用页面标签的时候，页面会加载过度

### ISSUE THREAD

**Issue by mmmwhy** [yscoder/hexo-theme-indigo#183]
https://imys.net/20161217/webpack-use-lodash.html#使用插件优化

比如这个页面，**使用插件优化**应该是可以看到的，但是加载过度，导致看不到标题了。

**Comment by yscoder** [comment]
get

**Comment by yscoder** [comment]
还是有问题。本页面内正常，从外部跳转进来不行。

**Comment by yscoder** [comment]
现在没问题了
