### ISSUE TITLE
多说要挂了！！！

### ISSUE THREAD

**Issue by weiyf** [yscoder/hexo-theme-indigo#185]
http://dev.duoshuo.com/threads/58d1169ae293b89a20c57241
![image](https://cloud.githubusercontent.com/assets/12067656/24152771/8f678b40-0e87-11e7-8f81-22fb157a98cf.png)

**Comment by yuangezhizao** [comment]
感谢提醒，

**Comment by yscoder** [comment]
一些备选评论系统：

* [畅言](http://changyan.kuaizhan.com/)
* [友言](http://www.uyan.cc/)
* [网易云跟帖](https://gentie.163.com/index.html)
* [来比力](http://laibili.com.cn/)

**Comment by Clarence-pan** [comment]
分享个畅言的插件安装：
 https://github.com/Clarence-pan/hexo-blog/commit/a6a85f89e17900d023c8c67020465830532f75bb

**Comment by Wensibob** [comment]
请问除了肠炎之外其他的评论系统如何安装？另外在多说的数据还能不能备份到新的系统呢？ @yscoder @Clarence-pan

**Comment by Clarence-pan** [comment]
@Wensibob 多说的数据应该可以导出，然后你看看其他系统是怎么导入的。

**Comment by Wensibob** [comment]
但是网站需要备案才可以使用畅言，悲催的我是海外服务器 @Clarence-pan

**Comment by ystyle** [comment]
@yscoder 已添加友言的rp, 希望可以合并一下

**Comment by ystyle** [comment]
@Wensibob 友言, 网易云跟帖可以导入多说的. 不过网易的要4小时生效, 友言的我导入失败.... 但最后还是选择了友言

**Comment by yscoder** [comment]
友言好像不支持 HTTPS

**Comment by yscoder** [comment]
https://github.com/imsun/gitment

**Comment by ckyOL** [comment]
不知这gitment如何作为插件添加进去

**Comment by Wensibob** [comment]
安装畅言之后在电脑端使用正常，但是在手机端点击登录的时候无法显示登录的对话框，这种情况除了谷歌Chrome浏览器之外都存在，我在手机端尝试访问你的网站，也遇到了同样的问题。请问如何解决？@Clarence-pan

**Comment by triplekiller** [comment]
为什么不用disqus呢，速度慢？ps: 我是新手

**Comment by yscoder** [comment]
@triplekiller disqus 被墙

**Comment by jasonzhang1986** [comment]
网易云跟帖接入指南 http://winxo.cn/20170409/displace_duoshuo.html 需要注意的一点是localhost的预览看不到comment，deploy后可以看到

**Comment by triplekiller** [comment]
怎么加入gitment支持呢？前端完全不懂:smile:

**Comment by ckyOL** [comment]
@triplekiller 自己动手写了个 gitment 支持，在我 fork 的项目里 [ckyOL/hexo-theme-indigo](https://github.com/ckyOL/hexo-theme-indigo)。现已合并至主分支。

**Comment by ckyOL** [comment]
@yscoder 已发起pr，希望合并

**Comment by heartsxin** [comment]
怎么使用友言啊，好像出不来

**Comment by weiyf** [comment]
亲爱的朋友们：

因公司业务发展需要，我们不得不遗憾地通知大家，云跟贴产品将于2017年8月1日停止服务。在此之前可以通过后台的数据导出功能导出自己站点的跟贴数据。感谢大家一直以来对云跟贴的支持与厚爱，对于此次产品关停给您带来的不便我们深表歉意，希望在网易其他产品与业务上，我们能继续为您服务！

网易云跟贴

2017年7月6日
