### ISSUE TITLE
Plugin load failed: hexo-generator-json-content

### ISSUE THREAD

**Issue by HaojunYinGeek** [yscoder/hexo-theme-indigo#187]
ERROR Plugin load failed: hexo-generator-json-content
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode

我的是mac电脑，hexo相关配置如下：
hexo: 3.2.2
hexo-cli: 1.0.2
os: Darwin 14.5.0 darwin x64
http_parser: 2.5.0
node: 4.2.1
v8: 4.5.103.35
uv: 1.7.5
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 56.1
modules: 46
openssl: 1.0.2d

**Comment by yscoder** [comment]
升级 Node 6.x
