### ISSUE TITLE
对数学公式的支持有问题

### ISSUE THREAD

**Issue by mmmwhy** [yscoder/hexo-theme-indigo#188]
较短的公式可以直接输出，较长的公式就会出现问题。

比如这种稍微长一些的

$$J(\theta_0,\theta_1 )=\frac1{2m} \sum_{i=1}^{m}(h_{\theta}(x^{(i)})-y^{(i)})^w$$

**Comment by yscoder** [comment]
中间一部分 `1 )=\frac1{2m} \sum` 被识别为斜体了，加了两个转义符后是可以的。

```
$$J(\theta_0,\theta\_1 )=\frac1{2m} \sum\_{i=1}^{m}(h_{\theta}(x^{(i)})-y^{(i)})^w$$
```

Hexo 所用的 markdown 引擎会把 `_` 作为斜体语法，也可以这样解决来避免渲染：

```
{% raw %}
$$J(\theta_0,\theta_1 )=\frac1{2m} \sum_{i=1}^{m}(h_{\theta}(x^{(i)})-y^{(i)})^w$$
{% endraw %}
```

**Comment by mmmwhy** [comment]
很有用，谢谢大佬~

**Comment by plmsmile** [comment]
可是如果是要去修改数学公式去支持博客显示的话，这样做不是很好呀。还有别的好的办法吗？
