### ISSUE TITLE
no css served

### ISSUE THREAD

**Issue by lukaMis** [yscoder/hexo-theme-indigo#19]
Hi

when i use this theme i get no css served in  public folder. Error is:
Failed to load resource: the server responded with a status of 404 (Not Found)

Css works when i use hexo server command but not in public folder when i put on my server. I do not have this issue with default hexo theme landscape. How can i resolve this? I really like this theme and would like to use it.

thnx
Luka

**Comment by yscoder** [comment]
This theme uses `less` as css preprocessor. You need to install it.

```
npm install hexo-renderer-less --save
```

**Comment by lukaMis** [comment]
Thank you.

**Comment by BestKind** [comment]
Thank you

**Comment by cuiyungao** [comment]
In my case, even though I installed the module "hexo-renderer-less", the CSS style still doesn't work. It works when using "hexo server", but it fails when using public server. How can I deal with this?

**Comment by yscoder** [comment]
@cuiyungao 

Run `hexo clean`, try agin.

**Comment by cuiyungao** [comment]
@yscoder It works now. Thanks.
