### ISSUE TITLE
添加404，但没有效

### ISSUE THREAD

**Issue by kazaff** [yscoder/hexo-theme-indigo#192]
是不是还缺少设置呢？

**Comment by yscoder** [comment]
- [Wiki - 404](https://github.com/yscoder/hexo-theme-indigo/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E6%B7%BB%E5%8A%A0404%E9%A1%B5%E9%9D%A2)
- #161
