### ISSUE TITLE
如何修改代码高亮配置

### ISSUE THREAD

**Issue by Allen-LPL** [yscoder/hexo-theme-indigo#193]
# 加入prettify高亮插件
如何修改代码高亮, 按照这个方法尝试修改了一次
[为hexo博客加入prettify高亮插件](http://ngudream.com/2016/09/13/hexo-install-prettify/)
虽然是yelee主体的修改方法, 不过我想它山之石可以攻玉, 所以就硬着头皮修改了, 不过没有成功.
>所以就想问一下, 代码高亮的正确修改方式, 如果这个课题比较麻烦, 就请告诉我js, css和模版的位置及书写方式, 我这里好自己研究下. 

**谢谢**.

**Comment by yscoder** [comment]
样式：`layout/_partial/head.ejs`
脚本：`layout/_partial/script.ejs`
移除 highlight 样式：`source/css/style.less:400`
其他还按那个文章说的做。

**Comment by xiaobailong24** [comment]
**脚本文件引入注意一定要在jquery脚本之后**
可是在脚本：layout/_partial/script.ejs 中哪个是jquery脚本呢？
感谢！

[layout/_partial/script.ejs](https://github.com/yscoder/hexo-theme-indigo/blob/card/layout/_partial/script.ejs)

**Comment by xiaobailong24** [comment]
```
<script src="//cdn.bootcss.com/node-waves/0.7.4/waves.min.js"></script>
<script>
var BLOG = { ROOT: '<%= config.root %>', SHARE: <%- theme.share %>, REWARD: <%- Boolean(page.reward) %> };
<%- partial('plugins/duoshuo-js', { enabled: theme.duoshuo_count }) %>
<% if (theme.cnzz){ %>
lazyScripts.push('//s95.cnzz.com/z_stat.php?id=<%-theme.cnzz %>&web_id=<%-theme.cnzz %>')
<% } %>
</script>

<script src="<%- url_for('/js/main' + (cache ? '.min': '') + '.js?v=' + theme_version()) %>"></script>
<% if (theme.search){ %>
<%- partial('search') %>
<script src="<%- url_for('/js/search' + (cache ? '.min': '') + '.js?v=' + theme_version()) %>" async></script>
<% } %>

<%- partial('plugins/mathjax') %>

<% if (theme.visit_counter) { %>
<script async src="//dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"></script>
<% } %>

<!--prettify代码高亮脚本引入-->
<script src="/plugins/prettify/prettify.js"></script>
<script type="text/javascript">
$(window).load(function(){
$('pre').addClass('prettyprint linenums').attr('style', 'overflow:auto;');
 prettyPrint();
})
</script>
<!--prettify代码高亮脚本引入-->

```
我的**script.ejs**脚本如上，加载的时候报错：
![error](https://cloud.githubusercontent.com/assets/9431974/26479403/834a7fb4-4205-11e7-942c-c794433be068.png)

求指导，万分感谢！

**Comment by yscoder** [comment]
@xiaobailong24 主题没有使用 jQuery，你需要把事件和修改样式的代码转成原生 js 写法。

**Comment by xiaobailong24** [comment]
@yscoder 感谢您的回复。请问是真么改吧？我对前端部太了解。
我查看了 **prettify.js** 是有 **prettyPrint()** 这个方法的
```
<!--prettify代码高亮脚本引入-->
<script src="/plugins/prettify/prettify.js" type="text/javascript">
    $(window).load(function(){
        $('pre').addClass('prettyprint linenums').attr('style', 'overflow:auto;');
        prettyPrint();})
</script>
```

**Comment by xiaobailong24** [comment]
最后选用了 **https://highlightjs.org** 高亮代码，但是背景色依旧是白色，即使使用黑色的背景色 显示效果还是白色，不能修改。

**Comment by xiaobailong24** [comment]
#207 
解决了，感谢。原谅我水平很菜。总结了一下
https://xiaobailong24.me/2017/05/26/Blog-Code-Highlightjs/

**Comment by fantasykai** [comment]
@xiaobailong24  我也在解决代码高亮的问题。按您的博客配置了下。没有启作用。貌似是没有引入Highlightjs 
配置点：
1.highlight 解压到blog目录下的plugins文件夹
2./blog/themes/indigo/layout/_partial/head.ejs  </head>最后添加
  
  <link rel="stylesheet" href="/plugins/highlight/styles/dracula.css">
  

</head>
3./blog/themes/indigo/layout/_partial/script.ejs 最后一行添加

<script src="/plugins/highlight/highlight.pack.js"></script>
<script>hljs.initHighlightingOnLoad();</script>


背景色部分是生效了的。。但是代码高亮没有生效

**Comment by xiaobailong24** [comment]
@fantasykai 是否移除 Hexo 默认高亮样式？
参考 #207 
把主题中的 cdn 配置为 false，这样使用的就是你修改过的样式。

**Comment by libsgh** [comment]
@xiaobailong24 @yscoder 设置了cdn为false 整站都找不到style.css没有样式了
