### ISSUE TITLE
能否将CSS，JS等文件上CDN

### ISSUE THREAD

**Issue by mmmwhy** [yscoder/hexo-theme-indigo#194]
将css,js等文件保存在cdn上，在设置中填写cdn的地址，可以加快页面加载速度。

**Comment by yscoder** [comment]
可以发到 npm。

**Comment by yscoder** [comment]
[CDN配置](https://github.com/yscoder/hexo-theme-indigo/blob/card/_config.yml#L133
)

暂时只支持脚本的 CDN，之后再完善。本地无效，只针对发布时替换为 CDN 链接。

**Comment by yscoder** [comment]
CSS 及 fonts 现在均可使用 [CDN](https://unpkg.com/hexo-theme-material-indigo@1.5.2/)。
