### ISSUE TITLE
能否在左侧加入类似Next主题隐藏侧栏和现实侧栏的功能

### ISSUE THREAD

**Issue by qinyuanpei** [yscoder/hexo-theme-indigo#2]
非常喜欢这个主题，希望作者能考虑在左侧加入类似Next主题隐藏侧栏和现实侧栏的功能，因为隐藏侧栏以后能够提供更为广阔的阅读空间，给你的Web设计点赞，作为一个前端渣我就只能帮到这里了！

**Comment by yscoder** [comment]
已经添加了大屏幕下的侧栏开关及文章页是否显示侧栏的配置项。
