### ISSUE TITLE
variable.less修改后无效果

### ISSUE THREAD

**Issue by PepcyCh** [yscoder/hexo-theme-indigo#207]
因为觉得文章显示有点窄，修改了theme/indigo/source/css/_partial/variable.less中的一些字段。
在"hero s"时有效果，但"hero d"后并没有效果（已经"hexo clean"）。
请问是什么地方会出问题？

**Comment by yscoder** [comment]
把主题中的 `cdn` 配置为 `false`，这样使用的就是你修改过的样式。

**Comment by libsgh** [comment]
@xiaobailong24 @yscoder 主题<code>cdn</code>设置为<code>false</code>后，无法显示，整站都无法显示了，/css/style.css?v=1.7.2 404
