### ISSUE TITLE
关闭分享后水波效果消失

### ISSUE THREAD

**Issue by weiyf** [yscoder/hexo-theme-indigo#21]
配置文件分享修改为false之后菜单水波效果消失，水波效果和分享直接关联了， 建议分开， 即使关闭分享功能， 菜单的水波效果仍然生效

**Comment by yscoder** [comment]
已修复，感谢反馈！

**Comment by weiyf** [comment]
还有一个问题是关闭分享之后， 文章toc因为分享模块隐藏， 往下滚动之后toc会向右边移动一段距离因为position: fixed;的原因吧，但是如果注释position: fixed;就不会有固定在右边的效果了

**Comment by yscoder** [comment]
因为右侧最外层没有固定宽度，现在加上了。
