### ISSUE TITLE
Some elements are redundant

### ISSUE THREAD

**Issue by johannjhang** [yscoder/hexo-theme-indigo#210]
<img width="699" alt="screen shot 2017-04-18 at 2 37 53 pm" src="https://cloud.githubusercontent.com/assets/1842626/25154248/c951575a-2444-11e7-81e6-c628635da802.png">

The bottom right author badge is a duplication of the profile information in the drawer menu.
The 「轉載請註明出處」is a duplication of copyright information. There's already a statement at the very bottom of the page.

<img width="437" alt="screen shot 2017-04-18 at 2 38 16 pm" src="https://cloud.githubusercontent.com/assets/1842626/25154252/ccd5f8d6-2444-11e7-9d82-601b11ba1163.png">

**Comment by yscoder** [comment]
Temporarily keep this custom content.
