### ISSUE TITLE
如何修改文章下方的转发声明

### ISSUE THREAD

**Issue by Wensibob** [yscoder/hexo-theme-indigo#213]
1、如何修改文章的转发声明。如下所示：
![20170424133117](https://cloud.githubusercontent.com/assets/24890876/25323635/22bc27d6-28f3-11e7-808c-6d3bbdf6e22f.png)

2、针对不同的文章，可以设计不同的转发声明吗？例如有的文章只要注明出处就可转发，有的文章需要联系作者取得作者同意之后才可转发。

**Comment by WingsXpOsid** [comment]
hexo\themes\indigo\_config.yml
第78行
