### ISSUE TITLE
文字详情里面遇到的问题

### ISSUE THREAD

**Issue by baowenqing** [yscoder/hexo-theme-indigo#214]
1.最后更新时间 是怎么写为中文的    默认的英文
2.点击您的姓名  可以跳转到首页 是怎么设置的呢

**Comment by yscoder** [comment]
1. 所有显示时间的格式与你在 `hexo/_config.yml` 中的配置有关
2. 默认就是如此

**Comment by baowenqing** [comment]
@yscoder  文章详情  点击你的姓名是到首页   我的点击了 是跳到了文章顶部    还有阅读全文 我的这里还是英文的标识 你的那点是怎么修改的呢

**Comment by yscoder** [comment]
需要配置 `hexo/_config.yml` 中的 `url`

**Comment by baowenqing** [comment]
好的 谢谢你
