### ISSUE TITLE
tags和categories页面显示异常

### ISSUE THREAD

**Issue by jasonzhang1986** [yscoder/hexo-theme-indigo#216]
indigo主题很不错，但在使用过程中遇到一个问题，我的tags和categories的页面显示异常，不能正常显示出全部来
http://jasonzhang1986.github.io/tags/
http://jasonzhang1986.github.io/categories/

**Comment by yscoder** [comment]
#154

**Comment by jasonzhang1986** [comment]
Thanks!

**Comment by fankangbest** [comment]
你好，你这问题怎么解决的啊？我搭建的环境访问tags, categories会变成http，导致访问出错。
