### ISSUE TITLE
云跟帖评论不显示

### ISSUE THREAD

**Issue by Wegome** [yscoder/hexo-theme-indigo#218]
云跟帖本地化后，
localhost测试评论正常，然而上传coding.net后，却不显示评论。

不知是什么问题。

**Comment by yscoder** [comment]
已经改好了，待会更新。 [预览](https://imys.net/20170318/vuex-cache-design.html#mutation优化)

**Comment by Wegome** [comment]
谢谢。辛苦了

**Comment by yscoder** [comment]
提交了，暂时先这样，有空了再集成 markdown。
