### ISSUE TITLE
Problem with tags

### ISSUE THREAD

**Issue by lukaMis** [yscoder/hexo-theme-indigo#22]
Hi

I get an error Cannot GET /tags/   when i click tags link in the sidebar. This happens even on clean hexo install with only theme changed from default.
Do i have to change something in _config.yml of your theme or in _config.yml of hexo itself? 

Tnx
Have a nice day.
Luka

**Comment by yscoder** [comment]
You need to create a `tags` page.

```
hexo new page tags
```

Modify this file metadata.

```
type: "tags"
noDate: true
comments: false
---
```

Please try again.

**Comment by lukaMis** [comment]
@yscoder Thank you.
Works as expected now. 
Your help is much appreciated as i am very new to hexo.
