### ISSUE TITLE
如何将tags的颜色固定为一种？

### ISSUE THREAD

**Issue by ier005** [yscoder/hexo-theme-indigo#220]
我自己将整体的配色由蓝色改为了比较冷的灰色调，所以card上五颜六色的标签与整体的风格显得格格不入。
自己对于前端设计涉猎不多，因此没有找到修改的地方。

请问如何将card上tag的颜色固定为一种？

另外提一点，作者的博客在移动端阅读界面，回帖的输入栏会将返回顶部按钮挡在后面。

**Comment by yscoder** [comment]
变量文件中已加入 tags 颜色。
