### ISSUE TITLE
开启https之后，js文件出现错误

### ISSUE THREAD

**Issue by ice1025** [yscoder/hexo-theme-indigo#222]
https://imice.me/
用的cloudflare
![](http://opf9zlth7.bkt.clouddn.com/17-5-9/88136541-file_1494311257833_1e23.png)
你好，类似这样的情况，是什么原因导致的呢...求解惑

**Comment by yscoder** [comment]
把DNS配置里关于邮箱的解析关掉

**Comment by ice1025** [comment]
@yscoder 
是cloudflare中吗？这里？
![](http://opf9zlth7.bkt.clouddn.com/17-5-9/20192415-file_1494314296082_cfef.jpg)
还是
![](http://opf9zlth7.bkt.clouddn.com/17-5-9/15755922-file_1494314763840_16fed.png)
关于邮箱的解析是指？
![](http://opf9zlth7.bkt.clouddn.com/17-5-9/3906516-file_1494322041402_617e.jpg)
这里？

**Comment by yscoder** [comment]
cloudflare

**Comment by ice1025** [comment]
我只添加了两条a记录一条cname，没邮箱ai

**Comment by yscoder** [comment]
![](https://cloud.githubusercontent.com/assets/12295378/25853927/ea5c0d06-3500-11e7-903b-afc9631378d0.jpg)

把这个关了

**Comment by ice1025** [comment]
get.非常感谢
