### ISSUE TITLE
插入图片错误

### ISSUE THREAD

**Issue by heliuphy** [yscoder/hexo-theme-indigo#224]
敲入 `![](/upload/1705112.jpg)` 博文中不显示图片，而是显示` {% image /upload/1705112.jpg '' '' %}`
如图：
![](http://op0n2nyjd.bkt.clouddn.com/1111111.jpg)
![](http://op0n2nyjd.bkt.clouddn.com/1111112.jpg)

但是用html标签`<html><img src="/upload/1705112.jpg"  alt="图片" /></html>`可以正常显示图片，只是这样就没有图片框了。
求解答！多谢~

**Comment by yscoder** [comment]
`scripts/plugins.js` 文件有更改吗？对照一下

**Comment by heliuphy** [comment]
哦哦，可以了，是我这儿的问题。谢谢~

2017-05-11 13:15 GMT+08:00 Yusen <notifications@github.com>:
