### ISSUE TITLE
请问如何将“继续阅读”放在另起一行的位置，而不是跟在摘要结尾

### ISSUE THREAD

**Issue by CoderLengary** [yscoder/hexo-theme-indigo#225]

**Comment by yscoder** [comment]
这个属于个人喜好，建议自行修改主题样式解决。[postlist.less#L108](https://github.com/yscoder/hexo-theme-indigo/blob/f616ca11aef320ce813e08f423ee186632ece850/source/css/_partial/postlist.less#L107)
