### ISSUE TITLE
当汉字一多时出现无限加载的情况

### ISSUE THREAD

**Issue by Dawnki** [yscoder/hexo-theme-indigo#226]
在一篇文章里，当汉字达到500+以上时，打开对应文章内容，出现无限加载动画，而文章内容空白的情况，F12打开开发者工具看，没有报错，在element那里查看post-content里面是有内容的，但是在实际页面里post-content是空白的

**Comment by Dawnki** [comment]
情况是出现在hexo server跑的本地服务器上，但是我部署到github上面跑却没有问题，能正常显示

**Comment by yscoder** [comment]
应该是某些插件未加载完成，可以看看 network 中存在 `pending` 状态的脚本有哪些

**Comment by Dawnki** [comment]
好奇怪，里面的资源status都是200，没有pending状态的， 但是页面就是空白
![image](https://cloud.githubusercontent.com/assets/14870739/26023307/81ab52c4-37eb-11e7-88fc-8059a71df076.png)

![image](https://cloud.githubusercontent.com/assets/14870739/26023322/a85f2526-37eb-11e7-996c-0b0e8e1796d7.png)

**Comment by yscoder** [comment]
没看到 js 的加载啊

**Comment by Dawnki** [comment]
恩，hexo server启动的本地服务器他没加载js（刷新过很多遍都没看见），部署到服务器里才有加载js，不知怎么回事....Orz

**Comment by yscoder** [comment]
有同步仓库吗？我说的是包括 hexo 部分的

**Comment by Dawnki** [comment]
https://github.com/Dawnki/withHexo  这个是我刚上传的仓库，包含hexo部分的，theme那里为了显示内部的东东，我theme里indigo的.git文件夹删掉了

**Comment by yscoder** [comment]
没发现啥问题...

**Comment by Dawnki** [comment]
或许是我hexo-server的问题吧，迟点重搞一下试试，O(∩_∩)O谢谢你的回复~~
