### ISSUE TITLE
用自定义页面代替主页面

### ISSUE THREAD

**Issue by Funarp** [yscoder/hexo-theme-indigo#227]
作者你好，请问我如何用一个已有的页面(通过hexo new page 生成的)，代替主页面呢？

**Comment by bilibilibl** [comment]
跳过渲染即可

2017年5月15日 19:45，"Funarp" <notifications@github.com>写道：

**Comment by Funarp** [comment]
我看到网上写的把index-generator什么的禁用然后在./source/建立index.md是这样么？？

**Comment by Funarp** [comment]
已解决，把 node_modules/hexo-generator-index 删除就好了
