### ISSUE TITLE
如何修改categories分类显示顺序？

### ISSUE THREAD

**Issue by Funarp** [yscoder/hexo-theme-indigo#229]
目前这套主题的categories 下每个分类下文章的排序是按照最近发布到最早发布排序的，请问如何反转显示的顺序呢？

**Comment by yscoder** [comment]
`categories` 数据是 `hexo-generator-category` 插件处理的，排序默认为时间倒序。
相关代码：[hexo-generator-category/blob/master/lib/generator.js#L13](https://github.com/hexojs/hexo-generator-category/blob/master/lib/generator.js#L13)

如果反转排序，需要 `hexo-generator-category` 插件支持自定义排序，或者自定义一个类似插件。

**Comment by Funarp** [comment]
哦哦，谢谢大神！
