### ISSUE TITLE
是否可以增加支持百度统计、腾讯分析，站内搜索功能

### ISSUE THREAD

**Issue by Phoenix-Ans** [yscoder/hexo-theme-indigo#23]
是否可以增加支持百度统计、腾讯分析，站内搜索功能

**Comment by yscoder** [comment]
百度统计就是在站点添加一段 js 代码，你可以手动添加到 `layout/_partial/script.ejs` 中。
想要在`_config.yml`中添加开关的话，就加个判断包裹。

如：
```
<% if (theme.bdtj){ %>
<script>
// 百度统计的代码
</script>
<% } %>
```

腾讯分析没用过，大概是一样的东西。

站内搜索可以考虑支持。

**Comment by Phoenix-Ans** [comment]
感谢~~！
