### ISSUE TITLE
如何修改代码块的样式

### ISSUE THREAD

**Issue by Athrun1027** [yscoder/hexo-theme-indigo#230]
请问是否可以修改文章内的代码显示风格呢

**Comment by yscoder** [comment]
修改 [css/_partial/highlight.less](https://github.com/yscoder/hexo-theme-indigo/blob/card/source/css/_partial/highlight.less) 中的变量值。

**Comment by Athrun1027** [comment]
请问有预设的方案可选吗，一个个改起来有点无力

**Comment by yscoder** [comment]
https://highlightjs.org/static/demo/
https://github.com/components/highlightjs/tree/master/styles

**Comment by Athrun1027** [comment]
您好，我对less不太了解，找到想改的css样式了，怎么修改highlight.less中的值

**Comment by Athrun1027** [comment]
您好，懂您的意思了，十分感谢
