### ISSUE TITLE
请问hexo可以做一个问答系统吗?

### ISSUE THREAD

**Issue by badboy-tian** [yscoder/hexo-theme-indigo#231]
请问hexo可以做一个问答系统吗? 类似知乎那样

**Comment by NoahDragon** [comment]
理論上是可行的，但與其用Hexo做，不如使用動態網頁架構。

**Comment by yscoder** [comment]
Hexo 的评论系统都是基于第三方插件的，属于外挂。用户不属于你，产生的内容也不属于你，对于内容你也没有绝对的控制权。

**Comment by badboy-tian** [comment]
好的 谢谢
