### ISSUE TITLE
如果把网站部署在oschina里面好像有问题,url不对

### ISSUE THREAD

**Issue by badboy-tian** [yscoder/hexo-theme-indigo#233]
在git.oschian里面创一个项目kotlin, 那么page地址就是 http://mwplay.oschina.io/kotlin  所以部署上去必须修改hexo/_config.yml里面的
```
url: http://mwplay.oschina.io
root: /kotlin/
```
这样的话 主题切换到indigo是会显示正常, 但是在具体的页面下面的部分好像显示不对
http://mwplay.oschina.io/kotlin/2017/05/21/hello-world/
![image](https://cloud.githubusercontent.com/assets/2835129/26280982/e5aad982-3e19-11e7-869b-e950f1f57f61.png)
这里显示的地址是不对的 http://mwplay.oschina.io/2017/05/21/hello-world/
应该是http://mwplay.oschina.io/kotlin/2017/05/21/hello-world/  少了一个kotlin. 不知道在哪里配置
![image](https://cloud.githubusercontent.com/assets/2835129/26280988/0c8258be-3e1a-11e7-9f08-5c6a3e4aacd6.png)
这里吗? 该怎么改呢

**Comment by badboy-tian** [comment]
这样导致分享出来的链接 也不对 地址里面少了kotlin

**Comment by yscoder** [comment]
问题是否还存在？

**Comment by yscoder** [comment]
把 `<%- url.replace(/index\.html$/, '') %>` 改为 `<%- page.permalink.replace(/index\.html$/, '')`
