### ISSUE TITLE
Google Analytics Bug

### ISSUE THREAD

**Issue by methol** [yscoder/hexo-theme-indigo#236]
这个代码感觉有bug啊

https://github.com/yscoder/hexo-theme-indigo/blob/card/layout/_partial/plugins/google-analytics.ejs

theme.google_analytics写的是true。
`ga('create', '<%- theme.google_analytics %>', 'auto');`应该换成`ga('create', '<%- theme.google_site_verification %>', 'auto');`吧

```
<% if (theme.google_analytics){ %>
<!-- Google Analytics -->
<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', '<%- theme.google_analytics %>', 'auto');
ga('send', 'pageview');
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>
<!-- End Google Analytics -->
<% } %>
```

**Comment by yscoder** [comment]
没有错，一个是谷歌统计，一个是站点验证。
