### ISSUE TITLE
这主题怎么修改样式了，如果换背影和导航栏上的颜色

### ISSUE THREAD

**Issue by yj3** [yscoder/hexo-theme-indigo#24]

**Comment by yscoder** [comment]
颜色变量都在这个文件中 `themes/indigo/source/_partial/variable.less`

**Comment by yj3** [comment]
OK ,Nice Thankyou

**Comment by ImportEffort** [comment]
@yscoder 改完以后如何生效呢？

**Comment by bilibilibl** [comment]
同问  我本地测试颜色修改浅蓝色对了 同步上去还是一样的深蓝色
已经执行过hexo clean

2017年4月22日 18:36，"Dev_wang" <notifications@github.com>写道：

**Comment by yscoder** [comment]
#207

**Comment by ImportEffort** [comment]
好的 修改成功了 感谢
