### ISSUE TITLE
页面上的深蓝色怎么改呀，改@primaryColor: #3f51b5; 这个咋没用

### ISSUE THREAD

**Issue by icql** [yscoder/hexo-theme-indigo#240]
想换个颜色，深蓝色有点压抑，希望可以自己改一下哈

**Comment by super3H** [comment]
[更改站点配色](https://github.com/yscoder/hexo-theme-indigo/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E6%9B%B4%E6%94%B9%E7%AB%99%E7%82%B9%E9%85%8D%E8%89%B2)

**Comment by super3H** [comment]
改了颜色后发现网易云评论无法加载了。。。
