### ISSUE TITLE
分享到微信的分享选项无法工作

### ISSUE THREAD

**Issue by CharlesLiuyx** [yscoder/hexo-theme-indigo#241]
无法分享到微信，显示Warning，是未知的URL

**Comment by yscoder** [comment]
手机扫描二维码转成文件看看链接是什么，或者把二维码图片保存起来找个识别二维码的网站识别一下。
目测站点链接配置问题。

**Comment by CharlesLiuyx** [comment]
大神好！站点链接配置这个是在主目录下的comfig.yml还是Indigo主题下的comfig.yml？
BYW，在站点中，除了Home可以在浏览器上显示小图标，其他页面（比如文章页面）都显示的页面图标，不是什么大问题，微微强迫症
