### ISSUE TITLE
如何更改文章页面的宽度width

### ISSUE THREAD

**Issue by chengxutianxia** [yscoder/hexo-theme-indigo#243]
我在本地修改主题中页面文章的宽度，启动服务后[http://localhost:4000](http://localhost:4000)中可以看到页面宽度修改成功。但是当我提交到github上的时候，博客页面宽度又变成主题默认的了。

请问作者，我该如何去修改这个属性才能在github Page中显现出来？

**Comment by yscoder** [comment]
配置：
```
cdn: false
```
