### ISSUE TITLE
每篇文章  页脚 处  返回 home 图标链接打开后，跳转s//这种形式，是什么问题？

### ISSUE THREAD

**Issue by 1-riverfish** [yscoder/hexo-theme-indigo#244]
![2017-06-03 10-28-11](https://cloud.githubusercontent.com/assets/27009694/26749865/688a48b0-4847-11e7-86ad-5a1b40b00198.png)

**Comment by yscoder** [comment]
![image](https://cloud.githubusercontent.com/assets/12295378/26749888/ef031b24-4847-11e7-9e33-050ae87f7a2c.png)

配置文件里的站点链接写错了吧

**Comment by 1-riverfish** [comment]
麻烦能具体说一下配置文件的名字吗？新手，没接触过java，谢谢！
