### ISSUE TITLE
中间文章主题部分能设置宽度吗，希望中间部分再宽一点，有时候写代码，不够宽，拖动滚动条费劲

### ISSUE THREAD

**Issue by reflyhight** [yscoder/hexo-theme-indigo#249]

**Comment by yscoder** [comment]
修改 [source/css/_partial/variable.less#L28](https://github.com/yscoder/hexo-theme-indigo/blob/card/source/css/_partial/variable.less#L28)

**Comment by reflyhight** [comment]
刚刚我试过这种方法了。本地运行Hexo时生效，用hexo deploy方式发布到到github的Pages里，访问时发现仍然不生效。用无痕模式访问，保证了没缓存。发布到线上宽度还是保持原样

**Comment by yscoder** [comment]
#243

**Comment by reflyhight** [comment]
解决。谢谢

**Comment by zhoufusong** [comment]
我按照这个方法修改该variable.less 和CDN 后整个布局就乱了，有啥需要注意的吗？

**Comment by Mosiki** [comment]
> 我按照这个方法修改该variable.less 和CDN 后整个布局就乱了，有啥需要注意的吗？

> 你的本地环境没有转less拓展
> 需要 npm install --save hexo-renderer-less
> 然后重新编译即可
