### ISSUE TITLE
移动端打赏功能的优化。

### ISSUE THREAD

**Issue by reflyhight** [yscoder/hexo-theme-indigo#250]
移动端，微信连接打开时，按理说直接长按，威信就能直接识别打赏了。可是由于有支付宝的二维码，导致识别出错。虽然说可以再拿出一个手机来对着威信扫描，但确实也需要两台手机在手。

改进意见：移动端只提供一个二维码，再加一个可以切换的按钮。

**Comment by reflyhight** [comment]
感谢大神的及时改进，不过刚我试了一下，似乎是不能切换支付宝。我用的是安卓。

**Comment by yscoder** [comment]
我也是安卓。
你试试我的站点： [链接](https://yscoder.github.io/20170507/data-sync-in-vue-single-page-application.html#推荐)

**Comment by reflyhight** [comment]
好的，重新弄了一下，很完美。谢谢。
