### ISSUE TITLE
请问如何把menu侧滑页面长度设置长一点

### ISSUE THREAD

**Issue by AZeC4** [yscoder/hexo-theme-indigo#256]
请问如何把menu侧滑页面长度设置长一点,就之前想放音乐木块的时候发现太小了,放不下一个播放器,要是把播放器设置小一点,文字就叠在一起了.

**Comment by yscoder** [comment]
主题照顾不到所有人，个人需要的定制化功能，不妨自己折腾一下。

看到你博客头部加了个背景图后，突显逼格啊。:+1:

**Comment by itgoyo** [comment]
嗯之前已经在menu改了样式,现在已经实现效果了,谢谢up主
