### ISSUE TITLE
请问关于markdown渲染的问题

### ISSUE THREAD

**Issue by triplekiller** [yscoder/hexo-theme-indigo#257]
@yscoder 

你好，我用vim写markdown，超过80个字符自动换行(hard wrap)，按道理渲染的时候markdown会忽略换行符，只将两个空格当换行，我本地用vim插件预览我写的markdown文章，不会在80个字符那渲染换行，但放到hexo博客里预览就在80个字符那换行了，感觉没有排满，不好看不知道是hexo问题还是hexo-theme-indigo问题还是我理解问题？

希望有vim+markdown大拿出现

谢谢了

**Comment by triplekiller** [comment]
感觉hexo渲染是用换行符来换行的，不是用markdown标准的两个空格来换行？？？

**Comment by yscoder** [comment]
我一直是用两个回车，theme 没有对 markdown 的渲染行为做任何干涉。

**Comment by triplekiller** [comment]
找到了
https://github.com/hexojs/hexo-renderer-marked

在_config.yml配置"gfm: false"关闭github flavoured markdown就可以了，看来GFM是直接将'\n'当换行，不是标准的markdown用两个或以上空格当换行

**Comment by yscoder** [comment]
ok
