### ISSUE TITLE
好多图标不能显示

### ISSUE THREAD

**Issue by XiaochenCui** [yscoder/hexo-theme-indigo#26]
github等很多图标在PC端无法显示
还有一个问题：写post时候如何设置tag?

**Comment by yscoder** [comment]
1. 出现图标无法显示的问题运行环境是什么？
2. tags设置: `tags: [html, css, js]`

**Comment by ActorJamesTsai** [comment]
你好！我是window环境，npm版本是 3.8.6，node 版本是 v6.1.0，git版本是2.8.2 
第一次部署Hexo能正常 hexo deploy，在githu clone你这个主题后，修改了相关配置，再hexo deploy就失败
报错如下：
(node:1568) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
ERROR Deployer not found: git
PS：我有执行过 npm install hexo-deployer-git --save（N次）

**Comment by yscoder** [comment]
@ActorJamesTsai 把 `hexo/_config.yml` 中的插件依赖删除，重试。

**Comment by ActorJamesTsai** [comment]
@yscoder 谢谢！
把 hexo/_config.yml 中的插件依赖删除，我还是无法deploy。
最后我重新拿一次hexo，再配置一次就可以deploy了，可能是我之前第一次操作有失误的地方（新手）
不过我还是很在意这句提示：**fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version**
你知道是什么意思吗？是不是要更新什么？

**Comment by yscoder** [comment]
@ActorJamesTsai   `graceful-fs`这个模块需要更新

**Comment by XiaochenCui** [comment]
@yscoder Ubuntu14.04 Firefox最新版本(不知道多少版本)
而且我这里打开你的博客也无法显示github图标

**Comment by XiaochenCui** [comment]
@yscoder 如图：
![_2016-05-13t14-31-16 916z](https://cloud.githubusercontent.com/assets/9801323/15251120/7e7c2bce-195a-11e6-9a35-89d9b2060d57.png)

**Comment by yscoder** [comment]
@XiaochenCui 你访问 http://fontawesome.io/icons/  搜索 github 看看图标显示不显示

**Comment by yscoder** [comment]
我找到问题原因了，参考：[Missing Brand Icons (Adblock Plus related issue)](https://github.com/FortAwesome/Font-Awesome/issues/1799)

是因为你安装了 Adblock ，Adblock 会过滤 SNS 相关的资源。按 `ctrl+shift+v` 打开可过滤项目就看到了。
