### ISSUE TITLE
怎么正确显示文章的最后更新时间

### ISSUE THREAD

**Issue by triplekiller** [yscoder/hexo-theme-indigo#260]
文章的最后更新时间除了可以在_config.yml中通过show_last_updated关闭显示外，有没有什么办法真实的显示每一篇文章的正确更新时间？

现在每次hexo deploy，每篇文章的最后更新时间都一样，都变成了最近一次deploy的时间，因为每次都要hexo generate重新生成静态页面然后重新push所有文件到服务端。比如我只修改文章1，然后hexo generate再push，但其他文章的最后更新时间也会变，这个怎么破？

**Comment by yscoder** [comment]
没有发现这种情况，比如我博客中一篇早期文章的更新时间依然在去年。[链接](https://imys.net/20150409/css-borde-shape.html)
也许跟操作系统有关，我平常用 win。建议到 hexojs 仓库寻找答案或开 issue。

**Comment by triplekiller** [comment]
我知道咋回事了
原因是我一直在改hexo或者indigo主题相关的配置，只要有改动，所有文章都会更新的，这个应该是正常的。只有待这些改动稳定后，再纯粹改文章内容，更新时间应该没有问题

**Comment by WengHaobin** [comment]
我发现复制了.md文件去-post文件夹，然后执行预览就会出现这样的现象，直接在终端hexo new 文章是不会出现这样的问题！
