### ISSUE TITLE
怎样为博客添加网站图标

### ISSUE THREAD

**Issue by superbigmice** [yscoder/hexo-theme-indigo#261]
网上找到的办法是：
     直接在hexo目录的source文件夹下把你的icon放进去就好了，图标名字叫favicon.ico 然后重新hexo g和hexo d就可以。
测试之后发现不管用，有什么解决办法吗？谢了

**Comment by yscoder** [comment]
试试  **站点链接/favicon.ico** 能不能访问到，如 `abc.com/favicon.ico`。
能访问到就没什么问题，清理缓存重启浏览器试试，或者找个新电脑或朋友的电脑访问。

**Comment by reflyhight** [comment]
去缓存可以改图片名，把配置里的图片名也改一下。
