### ISSUE TITLE
基于gitment添加评论，

### ISSUE THREAD

**Issue by superbigmice** [yscoder/hexo-theme-indigo#262]
在themes/indigo/_config.yml进行了如下编辑：
# 是否使用 gitment，https://github.com/imsun/gitment
gitment:
  owner: 29686614
  repo: comments.github.io
  client_id: 76c3bbcb2879d954fc73
  client_secret: 68c9bb46a9599446bb9d5e41365fcffda1390616

保存后，进行hexo g和hexo d ，显示如下：
   https://superbigmouse.github.io/2017/06/26/test/
提示Error not found 

comments.git.io是我新建的准备保存评论的仓库
是不是还有什么地方需要设置啊？

**Comment by yscoder** [comment]
https://github.com/imsun/gitment/issues/18
