### ISSUE TITLE
我的在本地运行正常，但是同步到git后就爆annot read property 'addEventListener' of null 这个错误

### ISSUE THREAD

**Issue by Dzer0** [yscoder/hexo-theme-indigo#264]
我的在本地运行正常，但是同步到git后就爆annot read property 'addEventListener' of null 这个错误
![error](https://user-images.githubusercontent.com/7724173/27579813-5d406f12-5b5b-11e7-8728-9ead397abbf4.png)

**Comment by yscoder** [comment]
站点地址发一下

**Comment by Dzer0** [comment]
https://zhizhebuyan.com

**Comment by yscoder** [comment]
同 #222

**Comment by Dzer0** [comment]
感谢！
