### ISSUE TITLE
开启toc不能显示文章正文

### ISSUE THREAD

**Issue by yyangdid** [yscoder/hexo-theme-indigo#268]
开启toc后不能显示文章的正文，左上角的菜单按钮也不能点击。好像正文是加载了的，但是好像显示文字是白色的，因为鼠标在正文处可以使用鼠标选择文字复制，不知道哪里的问题

**Comment by yyangdid** [comment]
找到问题了，我是使用org-mode格式，在导出org-mode的时候开启了emacs自带的toc，导致出错，关闭了就好了

**Comment by lyh543** [comment]
> 开启toc后不能显示文章的正文，左上角的菜单按钮也不能点击。好像正文是加载了的，但是好像显示文字是白色的，因为鼠标在正文处可以使用鼠标选择文字复制，不知道哪里的问题

有完全相同的问题。

```bash
$ npm list hexo-toc
hexo-site@0.0.0 /mnt/c/Users/lyh/Documents/Git/lyh543.github.io
└── hexo-toc@1.1.0
```

只要把 `config.yml` 文件改为

```yml
toc: false
```
就能正常使用，只是没有toc。

但是如果使用下面的配置：
```yml
toc:
  list_number: false  # 是否显示数字排序
```
只要有标题（无论标题等级），就会出现以上状况。当且仅当把所有标题删掉时，文章才能正常显示。
没有标题的文章没有 toc。

但是问题是，@yyangdid 说是 emacs 的问题，而我用 VSCode 也有同样的问题。

----------------------------------------------------

我最后解决的方案是，备份文件以后，重新 `hexo init blog` 和 `git clone git@github.com:yscoder/hexo-theme-indigo.git themes/indigo`，按照 indigo 作者的方法[安装依赖](https://github.com/yscoder/hexo-theme-indigo/wiki/%E5%AE%89%E8%A3%85#%E4%BE%9D%E8%B5%96%E5%AE%89%E8%A3%85)，然后再把配置文件、博客文件复制过去即可。

可能是我之前使用的另一种主题，切换主题的时候直接修改站点配置文件的 `theme` 选项，某些文件出现错误导致的问题。
