### ISSUE TITLE
多说评论框不显示

### ISSUE THREAD

**Issue by WengHaobin** [yscoder/hexo-theme-indigo#27]
在themes/_config文件已经改了duoshuo-key 为什么博客里面还是没有评论框呢？

**Comment by yscoder** [comment]
1. 确认 `duoshuo: duoshuo-key` 冒号和值之间有个半角空格；
2. 看看浏览器控制台有无异常信息。

**Comment by WengHaobin** [comment]
的确 控制台报错 参数错误 l @ static.duoshuo.com/embed.js:1 有遇到过么？

**Comment by WengHaobin** [comment]
解决了 多说的站名要和duoshuo-key保持一致

**Comment by yscoder** [comment]
好的
