### ISSUE TITLE
如何添加预加载页面？

### ISSUE THREAD

**Issue by pxim** [yscoder/hexo-theme-indigo#276]
我想添加一个预加载页面，在上面有些动画效果；现在我页面做好了，请问怎么设置页面层次在目前博客主页的外面一层？

**Comment by yscoder** [comment]
```
url: http://yoursite.com/path
root: /path/
```
参考：https://hexo.io/zh-cn/docs/configuration.html#网址

**Comment by arvin0** [comment]
没看懂，这个方法只是换了一个blog具体内容的根目录，没写哪里放欢迎页！像这样子的欢迎页 https://luuman.github.io/Home/H1/index.html ；不能和blog在一个仓库里？只能再建一个仓库，存放么？
