### ISSUE TITLE
content.json 

### ISSUE THREAD

**Issue by ActorJamesTsai** [yscoder/hexo-theme-indigo#28]
请问一下可以提供一下  **content.json**  这个文件吗？

**Comment by yscoder** [comment]
你说的是我博客上的？

**Comment by ActorJamesTsai** [comment]
是的。
你有没有一个教程是关于你怎么配置swiftype 搜索的？

**Comment by yscoder** [comment]
我最终没有使用 swiftype ，现在是基于一个 Hexo 插件实现的，这个 `content.json` 也是这个插件生成的。[hexo-generator-json-content](https://github.com/alexbruno/hexo-generator-json-content)

**Comment by yscoder** [comment]
之后我会把搜索功能集成到该项目内。

**Comment by ActorJamesTsai** [comment]
太好的，谢谢！
白忙活了一整天，哈哈
