### ISSUE TITLE
gh-page 点击标签、分类等无法访问，url必须是https才行

### ISSUE THREAD

**Issue by wywncdx** [yscoder/hexo-theme-indigo#286]
如题，直接使用gh-page的url访问时，会出问题，必须为https才行。我尝试在config文件中设置 标签、分类等为绝对路径，仍然无效。

**Comment by zsuperman** [comment]
我也遇到这个问题。点击标签跳转不了、你写https可以吗？

**Comment by zsuperman** [comment]
绝对地址也不行把。Cannot GET /tags/  我报的都是这个错。

**Comment by chengxutianxia** [comment]
哥们，https 不是很好嘛，没有 HTTPS的使劲想办法得到https。https相对安全

**Comment by wywncdx** [comment]
很奇怪，我昨天在家里试，必须用https才行，http就访问不到标签和分类，config写绝对路径也不行。
然后今天到了公司，结果试了下，能访问了……奇怪。。

**Comment by zsuperman** [comment]
你现在可以访问了吗？  设置的htts 绝对地址吗  我刚才还试了 不可以啊

**Comment by yscoder** [comment]
如果首次进入是 `http` 进入，但跳转是 `https` 的，把浏览器缓存清理一下，然后重启浏览器。

**Comment by wywncdx** [comment]
我的现在可以访问了。虽然是写的绝对地址，但是昨天在家里，同样访问不到。https://yscoder.github.io/ 
 作者的也访问不到。今天来公司，用公司电脑就都能访问了。我觉得可能是需要清缓存吧。
