### ISSUE TITLE
分享到第三方应用的文本中自带乱码“知锟叫猴拷一”

### ISSUE THREAD

**Issue by Phoenix-Ans** [yscoder/hexo-theme-indigo#29]
已保存md为UTF-8格式，仍然出现乱码   “知锟叫猴拷一”

**Comment by yscoder** [comment]
分享到哪里，有没有在线链接？

**Comment by Phoenix-Ans** [comment]
http://phoenix-ans.github.io/  

http://service.weibo.com/share/share.php?title=%E5%B0%8A%E9%87%8D%E5%8E%9F%E5%88%9B%EF%BC%8C%E7%BD%91%E9%A1%B5%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E5%BC%95%E5%85%A5%20%E7%9F%A5%E9%94%9F%E5%8F%AB%E7%8C%B4%E6%8B%B7%E4%B8%80&url=http%3A%2F%2Fyoursite.com%2F2016%2F05%2F11%2F%E5%B0%8A%E9%87%8D%E5%8E%9F%E5%88%9B%EF%BC%8C%E7%BD%91%E9%A1%B5%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E5%BC%95%E5%85%A5%2Findex.html&source=bookmark&appkey=2992571369&pic=http%3A%2F%2Fphoenix-ans.github.io%2Fimg%2Flogo.jpg&ralateUid=

**Comment by yscoder** [comment]
你打开 `layout/_partial/head.ejs`，看看 `<meta name="summary" >` 这里的 `content` 值是什么。
我看到你的页面源码上是乱码，分享的内容是从这个 `meta` 中读取的。

**Comment by Phoenix-Ans** [comment]
<meta name="summary" content="<%=(page.excerpt || config.description)%>">

**Comment by yscoder** [comment]
空的吗？正确的值是 `content="<%=(page.excerpt || config.description)%>"`

**Comment by Phoenix-Ans** [comment]
@yscoder  不是空的 与正确的值一致  刚才发的时候忘记了加代码插入格式所以显示是空的

**Comment by yscoder** [comment]
我懂了，你这篇文章是没有加`<!--more-->`标记，所以 `page.excerpt` 不存在。应该是 `config.description` 的原因，看看你的 `hexo/_config.yml`

**Comment by Phoenix-Ans** [comment]
@yscoder 我的description是中文的“知行合一”。。。。。不支持中文么~~

**Comment by yscoder** [comment]
不需要引号，冒号后有个半角空格。格式对不对？

**Comment by Phoenix-Ans** [comment]
@yscoder 
`title: Phoenix_Ann's Laboratory`
`subtitle: Getting Things Done`
`description: 知行合一`
`author: Phoenix_Ann`
`language: zh-CN`
`timezone:`

**Comment by yscoder** [comment]
看起来没有问题，我也用的中文，配置文件的编码是 utf8 吗

**Comment by Phoenix-Ans** [comment]
@yscoder 感谢提醒，原来是要把hexo/_config.yml保存成 UTF-8 编码

**Comment by yscoder** [comment]
你应该把 utf8 作为编辑器默认编码，以后就可以避免此类问题了。
