### ISSUE TITLE
字体无法加载

### ISSUE THREAD

**Issue by netyjq** [yscoder/hexo-theme-indigo#290]
最近发现字体无法加载了 

![image](https://user-images.githubusercontent.com/13848223/29237393-fbc4d75a-7f4f-11e7-9ee1-21a3a0b6d414.png)

**Comment by triplekiller** [comment]
我的也无法加载，是unpkg CDN的原因么？？？

浏览器访问https://unpkg.com/hexo-theme-material-indigo
提示如下：

**Cannot find main file "index" in package hexo-theme-material-indigo@1.6.12**

GET https://unpkg.com/hexo-theme-material-indigo@1.6.12/css/fonts/fontawesome/fontawesome-webfont.woff2?v=4.7 
(index):1 GET https://unpkg.com/hexo-theme-material-indigo@1.6.12/css/fonts/fontawesome/fontawesome-webfont.woff?v=4.7 
(index):1 GET https://unpkg.com/hexo-theme-material-indigo@1.6.12/css/fonts/fontawesome/fontawesome-webfont.ttf?v=4.7 403 ()

**Comment by yscoder** [comment]
确实，我试了下去掉 `query` 部分可以访问。

https://unpkg.com/hexo-theme-material-indigo@1.6.12/css/fonts/fontawesome/fontawesome-webfont.woff2

**Comment by yscoder** [comment]
那就去掉了，有版本号可以刷缓存，这个 `query` 无所谓了

**Comment by triplekiller** [comment]
现在可以了
为什么我没有更新你刚才提交的#290 commit，也可以了呢？会自动去unpkg上获取1.6.13的版本？那是不是想获取你的theme最新特性，不需要手动更新整个indigo仓库？谢谢！

**Comment by yscoder** [comment]
见：[plugins.js#L8](https://github.com/yscoder/hexo-theme-indigo/blob/card/scripts/plugins.js#L8) 
版本获取的是 `latest`，也就是最新版本。

如果是 css、js 资源文件的更改，你用 cdn 是不需要同步仓库的。
具体见：https://unpkg.com/hexo-theme-material-indigo@1.6.13/
