### ISSUE TITLE
用hexo发布的文章只能在手机上才能看

### ISSUE THREAD

**Issue by greedyhao** [yscoder/hexo-theme-indigo#291]
你好，我换到hexo后发现自己新发布的博文在电脑上看不了，只能在手机上看，我觉得很奇怪，还请给我一点帮助。

+ [这是可以在电脑上看的](http://greedyhao.cc/2017/08/13/工作-python-入门-2017-08-13-改变小数点位数/)
+ [这是不能在电脑上看的](http://greedyhao.cc/2017/08/14/工作-hexo-2017-08-14-利用hexo搭建博客/)

------------------------------
突然发现自己之前能在电脑上看的博文，好多都看不了了，我不清楚到底怎么回事

**Comment by OhYee** [comment]
能提供下没法正常访问的网页的md文件么
我猜是有一些特殊的字符导致hexo渲染错误了

另外 截断`<!--more-->` 不用加空格

**Comment by greedyhao** [comment]
@OhYee 感谢你告诉我截断符号的问题

我想起来我好像在我把 **hexo-renderer-markdown** 换成了 **hexo-renderer-markdown-it** 后才出现了问题，在我把这个插件换回去后，又修改了一下md文件在重新generate，网页就可以正常访问了。

[这是我刚刚那篇在电脑上访问不了的md](https://github.com/greedyhao/greedyhao.github.io/blob/master/%E5%88%A9%E7%94%A8hexo%E6%90%AD%E5%BB%BA%E5%8D%9A%E5%AE%A2.md)
