### ISSUE TITLE
unpkg cdn main.min.js timeout

### ISSUE THREAD

**Issue by gracefullight** [yscoder/hexo-theme-indigo#293]
![image](https://user-images.githubusercontent.com/11773683/29349539-8f7c65ba-8295-11e7-9f08-dda2bae0ad1d.png)

- [https://unpkg.com/hexo-theme-material-indigo@1.6.13/js/main.min.js](https://unpkg.com/hexo-theme-material-indigo@1.6.13/js/main.min.js) > timeout
- [https://unpkg.com/hexo-theme-material-indigo@1.6.13/js/main.js](https://unpkg.com/hexo-theme-material-indigo@1.6.13/js/main.js) > fine
- [https://unpkg.com/hexo-theme-material-indigo@1.6.12/js/main.min.js](https://unpkg.com/hexo-theme-material-indigo@1.6.12/js/main.min.js) > fine

What is the problem, can you upload the script again?

**Comment by MartinKolarik** [comment]
unpkg has been having many issues lately. You can always use jsDelivr instead, which works in a similar way but is more reliable: https://cdn.jsdelivr.net/npm/hexo-theme-material-indigo@1.6.13/js/main.min.js

**Comment by gracefullight** [comment]
@MartinKolarik  Thanks!!!
