### ISSUE TITLE
indigo默认支持什么图床吗，比如七牛啥的

### ISSUE THREAD

**Issue by triplekiller** [yscoder/hexo-theme-indigo#294]
还是只支持本地图床？有没有啥图床推荐的，谢谢

**Comment by itgoyo** [comment]
支持极简图床，也就是七牛。

**Comment by triplekiller** [comment]
@itgoyo 七牛据说绑定的域名要是备案的？麻烦

**Comment by yscoder** [comment]
七牛提供免费的三级域名，用自己的域名就要备案。

**Comment by triplekiller** [comment]
@yscoder 七牛或微博做图床，推荐哪个？还是有其他？谢

**Comment by triplekiller** [comment]
[微博图床][1]还是挺好用的，就是图片管理一般般
[1]: https://github.com/suxiaogang/WeiboPicBed

**Comment by yscoder** [comment]
一直用的七牛，也没用过其他，无法作出对比推荐。
