### ISSUE TITLE
css修改与CDN开启冲突

### ISSUE THREAD

**Issue by triplekiller** [yscoder/hexo-theme-indigo#295]
修改了source/css/_partial/reward.less的page-reward-btn，想把打赏button改大一些，结果发现本地预览生效，上传部署无效，最后发现原因应该是CDN导致，默认用的CDN上的style.css。问题来了，怎么样支持自定义这类修改，还能用CDN加速页面加载？谢谢！

**Comment by ghost** [comment]
modify Subject ->indigo\layout\_partial\head.ejs  file，modify 53line as follows
`<link rel="stylesheet" href="/css/style.css">`
修改主题下indigo\layout\_partial\head.ejs文件在第53行修改为如上即可，该文件编译后仅70K左右，不使用CDN也可以很快载入。

**Comment by OhYee** [comment]
针对@noesblog的方法
最新的版本已经可以不去修改head.ejs实现增加头部文件（方便管理）
如 https://github.com/yscoder/hexo-theme-indigo/pull/289
