### ISSUE TITLE
你好，请问archives这个模板文件在哪些地方有引用

### ISSUE THREAD

**Issue by ghost** [yscoder/hexo-theme-indigo#296]
目前想将贵主题的文章目录模板修改为博客主页，经过几次修改和将一些不需要的模板例如tags，archives复制为index模板，删除原index模板后，主页已经是文章目录的模板样式了，但是在public文件夹下仍然有archives的文件夹生成，请问这是什么原因?是还有其他地方的引用没有删除干净吗？

**Comment by yscoder** [comment]
卸载 `hexo-generator-archive` 插件。
