### ISSUE TITLE
请问搜索功能需要设置什么？

### ISSUE THREAD

**Issue by kohaiy** [yscoder/hexo-theme-indigo#299]
# 请问搜索功能需要设置什么吗？还是创建什么页面？我的网站的搜索框输入后回车并没有反应。求助！

**Comment by fuos** [comment]
应该是jsonContent设置问题。我的不设置搜索正常。如果设置插件，必须开启tag，可以看下我的配置
https://github.com/fuos/my-blog/blob/master/_config.yml
