### ISSUE TITLE
ERROR Process failed: layout/archive.ejs TypeError: Cannot read property 'compile' of undefined

### ISSUE THREAD

**Issue by Phoenix-Ans** [yscoder/hexo-theme-indigo#3]
输入以下命令时报错
>$ hexo g  
>INFO  Start processing  
>ERROR Process failed: layout/archive.ejs  
>TypeError: Cannot read property 'compile' of undefined

暂时解决方案：_config.yml中不配置插件依赖  
原始参考：[Maybe there's something wrong with your _config.yml? Could you post the _config.yml if you don't mind?](https://github.com/hexojs/hexo-renderer-jade/issues/4)

不知此解决方案是否可彻底解决而不引入新的问题~~

**Comment by yscoder** [comment]
如果你的 Hexo 版本是 3.2 的话，尝试降级到 3.1.1 解决。

[TypeError: Cannot read property 'compile' of undefined with Hexo 3.2.0 #1793
](https://github.com/hexojs/hexo/issues/1793)

**Comment by yscoder** [comment]
你的做法应该是没问题的，我现在把插件依赖删除后，可以正常使用。
Hexo 的插件加载方法我理解错了。

**Comment by Phoenix-Ans** [comment]
谢谢~~很喜欢你博客的设计风格~正在研究中~
