### ISSUE TITLE
clone theme

### ISSUE THREAD

**Issue by BladeCode** [yscoder/hexo-theme-indigo#30]
I want to use indigo theme, but not clone theme.
![Could not read from remote repository](http://7xs1zb.com1.z0.glb.clouddn.com/hexo_git.png)

**Comment by yscoder** [comment]
You need to create an SSH key , and set it to Github.

**Comment by BladeCode** [comment]
$ hexo clean
$ git clone https://github.com/yscoder/hexo-theme-indigo.git themes/indigo

**Comment by bigpo** [comment]
请问博主如何将两边的色块对齐，比如左边brand的边界比右边正文的标题的蓝色块要短一些，感觉不是很协调。。请看这个[图片链接](http://7xlckq.com1.z0.glb.clouddn.com/blog_color.png)

**Comment by yscoder** [comment]
@bigpo 没觉得有什么不协调。。你可以改 `主题/source/css/_partial/layout.less:51行`，把 `.avatar` 的宽高设为 `100px`。

**Comment by BladeCode** [comment]
hi,怎么在主页缩略显示文章，现在主页都是会将每个文章显示完

**Comment by yscoder** [comment]
在 md 文件中加入 `<!--more-->` 标记。

```
title: xxx
date: xxx
tags: [xxx]
---
文章摘要
<!--more-->
other……
```

**Comment by BladeCode** [comment]
Thank you very much
