### ISSUE TITLE
行间Mathjax公式无法Render

### ISSUE THREAD

**Issue by CharlesLiuyx** [yscoder/hexo-theme-indigo#301]
![image](https://user-images.githubusercontent.com/21956621/29746644-378ee414-8a96-11e7-805d-915d3b337e7a.png)
一些比较短的可以正常Render

在Typora内可以正常reander
![image](https://user-images.githubusercontent.com/21956621/29746654-8efd11d0-8a96-11e7-961b-24657cda86d3.png)

[链接](https://charlesliuyx.github.io/2017/05/27/AlphaGo%E8%BF%90%E8%A1%8C%E5%8E%9F%E7%90%86%E8%A7%A3%E6%9E%90/)

**Comment by yscoder** [comment]
也许与 #188 问题一样

**Comment by CharlesLiuyx** [comment]
已经解决！谢大神
