### ISSUE TITLE
分享功能无法成功分享

### ISSUE THREAD

**Issue by itgoyo** [yscoder/hexo-theme-indigo#304]
up主，使用你网站上的分享按钮是可以成功分享的，但是自己网站就无法分享，QQ分享提示“貌似出了些故障，麻烦重试一下”，我查看了一下share.ejs文件和你github提供的是一致的，还有什么地方会影响到么？[itgoyo.github.io](itgoyo.github.io)

**Comment by yscoder** [comment]
![image](https://user-images.githubusercontent.com/12295378/30045029-16a1b790-9234-11e7-8669-8a326a99783f.png)

我这里也是，是QQ的问题
