### ISSUE TITLE
关于如何在博文中嵌入js插件的问题

### ISSUE THREAD

**Issue by CharlesLiuyx** [yscoder/hexo-theme-indigo#305]
大神您好，求请教如果我想写一篇博文，其中有databases的表格，或者是D3.js的图表，我应该如何写的markdown文件？js代码可以直接嵌入到md中吗

**Comment by CharlesLiuyx** [comment]
如果我在设置中加入，layout:false，无法正确渲染

**Comment by yscoder** [comment]
直接 `<script></script>`

**Comment by CharlesLiuyx** [comment]
尝试了一下，并不能正确的读取到直接链接读取的datatable.js，应该只能本地下载之后引用，这种情况下就放在/theme/indigo/source/中的js，img，css中这样吗？比如我要把一个表格加上自定义的datatable.js，是不是需要修改一些文件啊？

**Comment by OhYee** [comment]
js放到`<BLOG>/sources/js/My.js`
`<script type="text/javascript" src="/js/My.js"></script>`
这样就可以应用了啊
哪个页面用到的话就加上这个

如果出现问题可以标记下不渲染
`{% raw %}<script type="text/javascript" src="/js/My.js"></script>{% endraw %}`
