### ISSUE TITLE
TOC显示问题

### ISSUE THREAD

**Issue by Wegome** [yscoder/hexo-theme-indigo#311]
你好！

![2017-09-22_162310](https://user-images.githubusercontent.com/6015834/30736078-efa4514c-9fb3-11e7-9406-879698cb60d9.jpg)
如上，这是你的博客，toc 在最新pc端chrome上，不会自动定位。

![2017-09-22_162217](https://user-images.githubusercontent.com/6015834/30736128-1937fda6-9fb4-11e7-8ac2-154991f2a0b4.jpg)
如上，toc在最新pc端chrome上，拉到最下端，会浮现在 footer 区块上方。

以上我的博客也如此。
但是在firefox上没问题。

**Comment by itgoyo** [comment]
我的站点也是这种情况
