### ISSUE TITLE
无法git下来

### ISSUE THREAD

**Issue by shuncon** [yscoder/hexo-theme-indigo#313]
# git clone git@github.com:yscoder/hexo-theme-indigo.git themes/indigoCloning into 'themes/indigo'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
麻烦git主看一下

**Comment by OhYee** [comment]
你这台电脑的ssh公钥在github上绑定了么
