### ISSUE TITLE
页面某些元素不显示

### ISSUE THREAD

**Issue by makesmallprogresseveryday** [yscoder/hexo-theme-indigo#314]
你的yscoder.github.io页面显示正常，但是imys.net页面不正常。点击imys.net页面某一篇文章，可以看到顶部没有显示标题，右侧目录会下移并留空白，右下角没有显示返回顶部。

**Comment by yscoder** [comment]
我这里是前者（yscoder.github.io）不正常，后者（imys.net）正常。前者几个月没有同步过了。

应该跟 chrome 版本有关，见 #306。
我跟随最新的 chrome 版本做了更新，#311。

之后我会再做一次兼容的修正。
