### ISSUE TITLE
请求加强移动端屏幕适配问题

### ISSUE THREAD

**Issue by wdpm** [yscoder/hexo-theme-indigo#32]
- 链接地址：
http://www.imys.net/20160303/hexo-nginx-auto-deploy.html
- 移动端竖屏显示效果：
http://7xowq8.com1.z0.glb.clouddn.com/Screenshot.png
- 问题描述：
代码端显示不全，请求完善。
- 其他
另外，博主MD风格的blog效果很赞。感谢。

**Comment by yscoder** [comment]
安卓版本和使用的手机浏览器是？

**Comment by wdpm** [comment]
安卓4.2 版本,QQ 浏览器6.1.0.1660和UC浏览器均测试了一下，代码段显示不全。
补充例子，例如：
```
a long single code segment.a long single code segment.a long single code segment.a long single code segment.a long single code segment.
```
单行代码显示没有问题。就是多行代码显示不全

**Comment by yscoder** [comment]
代码长度超过屏幕宽度会有横向滚动条，是这个问题吗？设定的就是这样的。

**Comment by wdpm** [comment]
不是滚动条问题。看这这张图片：
http://7xowq8.com1.z0.glb.clouddn.com/Screenshot.jpg
我从左向右滚动，只有一开始占屏幕宽度100%的那一部分能够显示(图中我已经让滚动条滚动了一段距离)
超过屏幕宽度100%的部分好像被截断了一样。

**Comment by yscoder** [comment]
身边没有安卓4.2的机子，是在 Wetest 上测的。
测试机是安卓4.2.2，QQ浏览器6.6，看上去正常。你可以升级浏览器试试。

![测试图](http://f.wetest.qq.com/gqop/395505/395505_11395_3544520544.jpg/0?token=xd4cc9041dfb4de7a2bd020a7462f2d6ff53f15e6dfu)

**Comment by wdpm** [comment]
升级浏览器版本后问题解决了。看来是浏览器问题。
