### ISSUE TITLE
关于主题样式问题

### ISSUE THREAD

**Issue by liuhao0813** [yscoder/hexo-theme-indigo#323]
我clone下来，怎么出现这样得问题，好像JS和CSS都不生效，请问一下什么原因
![image](https://user-images.githubusercontent.com/5961039/31537521-0bb3912c-b035-11e7-85ba-c05491f911b3.png)

**Comment by SimonAKing** [comment]
没有安装Less解析包吧？

**Comment by SimonAKing** [comment]
作者有文档的，你按照文档来 https://github.com/yscoder/hexo-theme-indigo/wiki

**Comment by ryanzhouff** [comment]
需要安装less依赖，严格按照配置文档来
