### ISSUE TITLE
博客加载速度慢

### ISSUE THREAD

**Issue by ryanzhouff** [yscoder/hexo-theme-indigo#326]
博客响应的时间过长，导致加载内容太慢。我用Develop tool查看了一下，发现主要是`unpkg.com`这个cdn导致的。如图：
![toolong](https://user-images.githubusercontent.com/29921478/31596545-bd4bc782-b275-11e7-8ab6-7deab4ec62a3.png)
有时候，甚至会加载失败：
![timeout](https://user-images.githubusercontent.com/29921478/31596554-cd42e6ca-b275-11e7-9609-99af0786131b.png)
所以，如何去更换`CDN`，比如更换成国内的？

**Comment by scarleast** [comment]
老哥，怎么解决的~
