### ISSUE TITLE
图标无法显示问题(已关闭adb)

### ISSUE THREAD

**Issue by XiaochenCui** [yscoder/hexo-theme-indigo#33]
运行环境:ubuntu14.04
http://www.cuixiaochen.com/
第四行的[bar-chart](http://fontawesome.io/icon/bar-chart/)图标无法显示

**Comment by XiaochenCui** [comment]
设置：
menu:
  home:
    text: 主页
    url: /
  archives:
    text: 文章列表
    url: /archives
  tags:
    text: 标签
    url: /tags
  bar-chart:
    text: 豆瓣爬虫
    url: https://github.com/XiaochenCui/Web_Crawler_Python3
    target: _blank

**Comment by yscoder** [comment]
重新 pull 一下，我更新了图标文件。
