### ISSUE TITLE
尴尬, 站点配置中的语言怎么改都是显示的英文

### ISSUE THREAD

**Issue by geekqian** [yscoder/hexo-theme-indigo#330]
# language: zh-tw  
# language: zh-Hans
# language: zh-hk

都试过, 然后hexo clean 再重新部署依然无效. 

切换到隔壁的 Next 主题没有这问题, 但还是喜欢 indigo, 所以来问问怎么解决?

**Comment by yscoder** [comment]
大小写敏感，目前支持：

```
zh-CN
zh-TW
en
```
