### ISSUE TITLE
文章页宽度无法修改

### ISSUE THREAD

**Issue by RonaldZhao** [yscoder/hexo-theme-indigo#331]
头部引用style.css的时候总是这样：

`<link rel="stylesheet" href="//unpkg.com/hexo-theme-material-indigo@latest/css/style.css">`

而不是直接从我的目录下引用，这是怎么回事？
想修改文章宽度都改不了。求解
附blog链接：https://blog.jesuszhao.top/

**Comment by yscoder** [comment]
配置 `cdn: false`，使用本地资源。
