### ISSUE TITLE
如图，copyright右下方的按钮指向问题

### ISSUE THREAD

**Issue by WengHaobin** [yscoder/hexo-theme-indigo#342]
![image](https://user-images.githubusercontent.com/16800049/33616868-210e88f2-da19-11e7-96e7-f51b0cf0b6f3.png)

@yscoder 大佬，你好！如图，copyright右下方的按钮指向的链接后面多了一截，请问是在哪里设置去掉呢？

**Comment by yscoder** [comment]
站点配置：`url`

**Comment by WengHaobin** [comment]
ok了 谢谢大佬
