### ISSUE TITLE
toc渲染换行

### ISSUE THREAD

**Issue by wlx200510** [yscoder/hexo-theme-indigo#343]
仔细查看了dom结构  发现跟作者页面上渲染效果不一致  出现了标题文字渲染到了外面的a标签的问题

**Comment by yscoder** [comment]
链接

**Comment by wlx200510** [comment]
http://geekarl.gitee.io/card_hexo_blog/  点开文章可以看到

**Comment by yscoder** [comment]
运行 `hexo -v`，看一下环境信息

**Comment by wlx200510** [comment]
hexo: 3.4.3
hexo-cli: 1.0.4
os: Windows_NT 10.0.15063 win32 x64
http_parser: 2.7.0
node: 6.5.0
v8: 5.1.281.81
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h

**Comment by wlx200510** [comment]
我看了下渲染模板 没找到细节的dom模板 没找到详细的dom嵌套生成的逻辑

**Comment by yscoder** [comment]
`toc`是`hexo`内置的渲染函数。

见[#2875](https://github.com/hexojs/hexo/pull/2875/files)，这个提交把`.text()`换成了`.html()`，以至于把标题内的 `.headerlink` 也插入 `toc` 中了。由于 `a` 不能嵌套 `a`，就出现了你这种情况。

你可以暂时降级解决，等我提交兼容性修改，或向 `hexo` 提 issue。

**Comment by yscoder** [comment]
这个提交已经把 [hexo文档](https://hexo.io/docs/index.html) 右侧的 `toc` 搞的不能用了 :joy:

**Comment by yscoder** [comment]
@NoahDragon 能否提供一下修改？

**Comment by wlx200510** [comment]
这个是hexo的代码问题 有人提hexo的pull request

**Comment by WengHaobin** [comment]
我这里好像也有这个问题(ಥ_ಥ) 
hexo: 3.4.2
hexo-cli: 1.0.4
os: Darwin 17.3.0 darwin x64
http_parser: 2.7.0
node: 8.9.1
v8: 6.1.534.47
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2m
icu: 59.1
unicode: 9.0
cldr: 31.0.1

**Comment by wlx200510** [comment]
看到hexo有人提pull request了  估计很快就能改了

**Comment by NoahDragon** [comment]
@yscoder 谢谢，代码已合并，下个版本应该会修复。

**Comment by hxlzpnyist** [comment]
怎么解决这个问题啊 ？ 需要升级 hexo 版本吗

**Comment by NoahDragon** [comment]
@hxlzpnyist 是的，需要升级Hexo

**Comment by hxlzpnyist** [comment]
@NoahDragon  已解决 谢谢

**Comment by WengHaobin** [comment]
hexo: 3.4.3
hexo-cli: 1.0.4
os: Darwin 15.6.0 darwin x64
http_parser: 2.7.0
node: 9.2.0
v8: 6.2.414.44-node.11
uv: 1.16.1
zlib: 1.2.11
ares: 1.13.0
modules: 59
nghttp2: 1.25.0
openssl: 1.0.2m
icu: 60.1
unicode: 10.0
cldr: 32.0
tz: 2017c
已经更新到这里，还是有这个问题呀😂
