### ISSUE TITLE
tags的index页面和categories的index的页面没有啊

### ISSUE THREAD

**Issue by smilelight** [yscoder/hexo-theme-indigo#345]
作者您好，您写的这款主题我非常喜欢，首先向您致以崇高的谢意，我前端只懂一点点，其他都挺好不过我发现当给文章设定了tags和categories属性之后，发现通过文章的tags和categories属性可以显示分tags和分categories，不过总的页面就还是404了。
如：
![架构略图](http://www.iamlightsmile.com/problem/pro1.png)
以及tags和categories的图：
![categories总图](http://www.iamlightsmile.com/problem/pro2.png)
![categories分图](http://www.iamlightsmile.com/problem/pro3.png)
![tag总图](http://www.iamlightsmile.com/problem/pro5.png)
![tag分图](http://www.iamlightsmile.com/problem/pro4.png)
我觉得应该肯定是我的问题，但是也不知道怎么解决，所以十分恳求您的帮助！万分感谢！

**Comment by yscoder** [comment]
#154

**Comment by smilelight** [comment]
额，自己没有好好阅读文档，问题已解决，麻烦您了，十分感谢！！！ @yscoder
