### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by wenxhwork** [yscoder/hexo-theme-indigo#35]
希望能在menu里增加categories的页面

**Comment by koakumaping** [comment]
我特意试了下，确实不支持。categories目录下没有生成index.html。为什么呢？

**Comment by bi-kai** [comment]
我也希望添加分类，默认主题都是支持的呀

**Comment by cstsinghua** [comment]
categories目录下没有生成index.html。又想在menu里面添加各种分类的连接，只是不知道fontawesome图标有哪些啊(随便写一个分类，但是就menu这里就是普通的文字而非fontawesome图标)，自己想定制的话，应该怎么做，对于前端不是很熟悉

**Comment by yscoder** [comment]
@cstsinghua [菜单项的添加与图标使用](https://github.com/yscoder/hexo-theme-indigo/wiki/%E9%85%8D%E7%BD%AE#%E5%B7%A6%E4%BE%A7%E8%8F%9C%E5%8D%95)。

**categories**  会在下一次提交加上，最快是这个周末。

**Comment by Phoenix-Ann** [comment]
如何设置 categories

**Comment by yscoder** [comment]
@Phoenix-Ann 目前可以在文章列表与文章页显示分类名，会生成单个分类的归档页。

比如你有个 **JS**  的分类，访问的URL为 `http://yourblog.com/categories/js`。

所有分类的汇总页还没有。考虑到分类数量不会太多，一般只是用于在菜单处链接。

**Comment by terge** [comment]
同样，等分类

**Comment by wudaijun** [comment]
确实有这个需求，希望作者有时间能完善一下。谢谢。

**Comment by ymqy** [comment]
加入的categories貌似不能用，小白，求教

**Comment by my101du** [comment]
同等 /categories 页面能自动显示所有分类

**Comment by christopher-ustb** [comment]
对hexo很不熟悉，如果自己想生成一个/categories 页面能自动显示所有分类应该如何开始呢

**Comment by my101du** [comment]
@christopher-ustb 我以前用过 Next 这个主题，它有能自动得到所有分类并保存到 /categories/index.html 的功能，但是我没有细读代码，不知用的什么原理。有兴趣你可以看看

**Comment by christopher-ustb** [comment]
@my101du 感谢你的回复。这个主题我已经看过，在github上应该是star数最多的hexo theme。但是hexo-theme-indigo这个靛蓝色的material design风格的主题我十分喜欢。另一方面，我觉得hexo十分神奇，希望能窥探他的一二秘密

**Comment by yscoder** [comment]
新版的分类页长这样：

![image](https://cloud.githubusercontent.com/assets/12295378/19628700/5309d646-9996-11e6-8653-2ec7a5a9338e.png)

数目过多，超过一行时，点击右侧，可显示全部：

![image](https://cloud.githubusercontent.com/assets/12295378/19628706/82703b96-9996-11e6-99e7-deabb928032e.png)

移动端，可以左右滑动，寻找你感兴趣的分类或标签。
我没有太多分类，以标签页为例：

![image](https://cloud.githubusercontent.com/assets/12295378/19628728/da9dd878-9996-11e6-8799-baac35524b5a.png)

**Comment by christopher-ustb** [comment]
@yscoder 你好，我看了你的demo站，由于你没有放置 categories/链接，我手动改动url为http://imys.net/categories/访问后返回404错误

**Comment by yscoder** [comment]
@christopher-ustb 当博客中一个分类都没有时，就不会生成 categories 相关页面。上面的图是我本地测试时截得。

**Comment by yscoder** [comment]
另外，和 tags 一样，categories 开启需要手动创建一个页面，参考：[开启分类页](https://github.com/yscoder/hexo-theme-indigo/wiki/%E5%AE%89%E8%A3%85#%E5%BC%80%E5%90%AF%E5%88%86%E7%B1%BB%E9%A1%B5)

**Comment by christopher-ustb** [comment]
@yscoder 你好，新的categories页真是太棒了。
但我的站点出现一个问题：
与你的站点 http://imys.net/categories/ 不同，我的站点部署在github.io上并且带了子路径，于是，点击tags-bar.ejs的“全部”标签头时，由于你的代码直接使用`/<%=type %>`作为href，而将我导向了不带子路径的地址：mydomain/tags，而不是mydomain/subdirectory/tags，于是404
ps：我已在hexo根目录的_config.yml配置了url与root属性

不知道这是一个小bug还是有我不知道的配置被遗漏了

**Comment by yscoder** [comment]
@christopher-ustb 我疏忽了，已修复。

**Comment by christopher-ustb** [comment]
@yscoder search.js中获取content.json也有同样的路径问题

**Comment by yscoder** [comment]
@christopher-ustb 已更新

**Comment by christopher-ustb** [comment]
@yscoder 现在搜索结果有了，但是结果item上的href缺少了子路径

**Comment by yscoder** [comment]
@christopher-ustb 有其他问题另开 issue，跑题了，更新 1.1.7
