### ISSUE TITLE
请问如何修改monospace字体？

### ISSUE THREAD

**Issue by lightingghost** [yscoder/hexo-theme-indigo#351]
我尝试过的方法如下：

在主题文件夹下的`source\css\fonts` 放入目标字体
在 `source\css\_partial\` 添加字体描述 `input.less`
```
@font-face {
    font-family: "Input";
    src: local('Input'), local('Input-Regular'),
        url("@{font-input}/Input-Regular.ttf") format("truetype");

    font-weight: 200;
}
```
并在`source\css\style.less` 中导入`input.less`。
然后在`source\css\_partial\variable.less` 中修改如下字段
```
@font-code: Input, Monaco, courier, monospace;
```
然而在本机服务器能看到相应字体，上传到github后访问页面， 发现并没有使用相应字体。

请问您可以帮忙看一下这个问题吗？谢谢。

**Comment by yscoder** [comment]
[常见问题](https://github.com/yscoder/hexo-theme-indigo/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E8%87%AA%E8%A1%8C%E4%BF%AE%E6%94%B9%E6%A0%B7%E5%BC%8F%E7%BA%BF%E4%B8%8A%E4%B8%8D%E7%94%9F%E6%95%88)
