### ISSUE TITLE
友言的api地址已经更改了

### ISSUE THREAD

**Issue by catch6** [yscoder/hexo-theme-indigo#352]
友言的api地址已经更改了
原来的http://jsapi.uyan.cc/?url= 会报502 Bad Gateway
新的地址是http://v2.uyan.cc/code/uyan.js?uid= 请修改下

**Comment by may7be** [comment]
而且友言不知道为什么使用不了

**Comment by yscoder** [comment]
[源码位置](https://github.com/yscoder/hexo-theme-indigo/blob/card/layout/_partial/plugins/uyan.ejs#L5)

就是你说的地址。我没用过友言，应该是其他问题导致不能用。
