### ISSUE TITLE
首页摘要没有Markdown渲染

### ISSUE THREAD

**Issue by CS-Tao** [yscoder/hexo-theme-indigo#357]
文章的首页摘要没有进行Markdown渲染，好像也没有文字换行功能，作者可以考虑添加一下该功能吗？
很喜欢这个主题。

**Comment by yscoder** [comment]
[配置：文章摘要](https://github.com/yscoder/hexo-theme-indigo/wiki/%E9%85%8D%E7%BD%AE#%E6%96%87%E7%AB%A0%E6%91%98%E8%A6%81)

**Comment by CS-Tao** [comment]
哦哦这样啊，是我没注意到。很完美的主题！
