### ISSUE TITLE
Tags里的"全部"没有生成对应的.html文件

### ISSUE THREAD

**Issue by Qu000** [yscoder/hexo-theme-indigo#378]

**Comment by Qu000** [comment]
Tags里的"全部"，打开为404页面，我看了目录，发现没有生成对应的.html，而其他的Tag均显示正常，这是什么地方出问题了呢？

**Comment by QianShengWu** [comment]
tags中添加  layout: tags

**Comment by neverjust** [comment]
我也有这个问题 ，按照楼上说的 在/theme/indigo/_config.yml 里的tags:下添加了layout: tags 
tags文件夹内 还是没有生成index.html文件
点击博客中的tags还是只有 Cannot GET /tags/

**Comment by yscoder** [comment]
[开启标签页](https://github.com/yscoder/hexo-theme-indigo/wiki/%E5%AE%89%E8%A3%85#%E5%BC%80%E5%90%AF%E6%A0%87%E7%AD%BE%E9%A1%B5)

搜下 issues 或者看 wiki 都能找到
