### ISSUE TITLE
请问如果有人在我博文下面评论了, 能办法能给我发个邮件吗? 这种功能如何做呢

### ISSUE THREAD

**Issue by badboy-tian** [yscoder/hexo-theme-indigo#380]
用的是Valine

**Comment by yscoder** [comment]
[Valine 评论系统中的邮件提醒设置](https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE)
