### ISSUE TITLE
打开标题显示“是鬼去哪里了”

### ISSUE THREAD

**Issue by StevenIIV** [yscoder/hexo-theme-indigo#381]
![canvas](https://user-images.githubusercontent.com/31725409/37866336-4e1fc328-2fc4-11e8-8cc7-73d19bb88380.png)

**Comment by PiterFan** [comment]
在_config.yml关闭动态标题：
```
# 动态定义title
title_change: false
#  normal: (つェ⊂)咦!又好了!
#  leave: 死鬼去哪里了！
```
