### ISSUE TITLE
请问如何修改主题风格，指修改主题颜色，比如粉色

### ISSUE THREAD

**Issue by smilelight** [yscoder/hexo-theme-indigo#387]

**Comment by smilelight** [comment]
我发现相关的设置在_partial文件夹下的variable.less文件中，我也修改了相关变量的值如@darkPrimaryColor: #FFC0CB;@primaryColor: #FFB6C1;将颜色设置为粉色，可是生成的还是蓝色主题，对于less我不是很了解，我想为一位女性朋友做一个个人博客网站，感谢作者及其他爱好者的热心解答，谢谢！

**Comment by yscoder** [comment]
顺序执行以下命令

```
hexo clean
hexo g
```

**Comment by smilelight** [comment]
![360 17100816105408](https://user-images.githubusercontent.com/17498154/38969497-2e74088c-43c3-11e8-8955-d27420026170.png)
![360 17321130106145104](https://user-images.githubusercontent.com/17498154/38969504-34cf1f64-43c3-11e8-89ec-156afaf3024b.png)
发现还是不行呀，已经顺序执行过相关命令了。。。

**Comment by yscoder** [comment]
`cdn: false` 配过了吗

**Comment by smilelight** [comment]
没有。。。额，刚发现，需要配置，很感谢您的热心帮助！谢谢作者大佬~
