### ISSUE TITLE
文章内容和右侧标题导航出现叠加

### ISSUE THREAD

**Issue by BladeCode** [yscoder/hexo-theme-indigo#39]
平凡出现文章内容和右侧标题导航叠加问题，通过右下角的返回顶部，此时又显示正常
![内容叠加](http://7xs1zb.com1.z0.glb.clouddn.com/indigo-bug.png)

**Comment by yscoder** [comment]
使用的浏览器是？或者页面链接给我发一下。

**Comment by BladeCode** [comment]
chrome可以悬停右侧文章导航，firefox右侧文章导航，不能悬停，我是页面部署在本地

**Comment by yscoder** [comment]
我发现分享未设置时有时会出现这种情况，你是不是属于此类？

**Comment by BladeCode** [comment]
对的，我确实取消了分享设置

**Comment by yscoder** [comment]
已修复
