### ISSUE TITLE
Mac 下 icon 无法正常显示

### ISSUE THREAD

**Issue by Airsaid** [yscoder/hexo-theme-indigo#390]
我的环境：

1，Mac 系统版本 0.13.4。
2，Chrome 版本 65.0.3325.181（正式版本）。
3，广告插件已经关闭。

**Comment by Airsaid** [comment]
<img width="222" alt="qq20180423-103336 2x" src="https://user-images.githubusercontent.com/15967150/39104215-dcdf1a6c-46e1-11e8-80c6-d5deb8f709f5.png">

显示如上图，作者的博客显示也是如此。用手机访问则正常显示。

**Comment by Airsaid** [comment]
补充：https://fontawesome.com/ 上的图标可以正常显示。

**Comment by yscoder** [comment]
![image](https://user-images.githubusercontent.com/12295378/39104255-13d3967e-46e2-11e8-9aca-8eea1b8ddc4c.png)

网络环境问题，我这里是正常的。你可以把 cdn 关了，用你的本地文件。
