### ISSUE TITLE
每次访问都有一个弹窗 " Browsersync connected "

### ISSUE THREAD

**Issue by netyjq** [yscoder/hexo-theme-indigo#402]
![tim 20180504133354](https://user-images.githubusercontent.com/13848223/39614146-0aa98f1a-4fa0-11e8-9582-95a88286f816.png)

**Comment by yscoder** [comment]
因为你装了 browsersync 插件

**Comment by netyjq** [comment]
这个插件我真没装，我怀疑是开启了主题的某项配置导致的。

**Comment by yscoder** [comment]
hexo 下的 package.json 看一下

**Comment by netyjq** [comment]
额，谢谢大神，我小白一个，还以为你说的是chrome 插件

**Comment by netyjq** [comment]
还有一个问题，升级后加入阅读次数了，但这个是刷新一次就加一次的。

**Comment by yscoder** [comment]
这是插件提供的功能，跟主题无关
