### ISSUE TITLE
请问如何更换博客底部的版权协议

### ISSUE THREAD

**Issue by hubojing** [yscoder/hexo-theme-indigo#406]
您好！
我希望更换 知识共享 署名 - 非商业性 - 相同方式共享 4.0 国际协议 为其它的协议，我查看了\layout\_partial\footer.ejs文件，
    <div class="top">
        <%- partial('plugins/site-visit') %>
        <p>
            <% if ((config.feed) && (config.feed.path.length)) { %>
                <span><a href="<%- url_for(config.feed.path) %>" target="_blank" class="rss" title="rss"><i class="icon icon-lg icon-rss"></i></a></span>
            <% } %>
            <span><%- __('footer.license') %></span>
        </p>
    </div>

这个config.feed是什么？以及footer.license是在哪里呢？谢谢指教。

**Comment by yscoder** [comment]
license 的定义在 languages 目录中；
feed 是 rss 描述文件，不在主题配置就在站点配置，你找找。

**Comment by jerryc127** [comment]
直接在language文件夹，找到你应用的语言文件
修改license 的文字就可以了

**Comment by hubojing** [comment]
谢谢！
