### ISSUE TITLE
配置ejs后，底部没靠拢，怎么解决？

### ISSUE THREAD

**Issue by jerryc127** [yscoder/hexo-theme-indigo#410]
自己用了其他主题的“友情链接” 的 ejs
https://github.com/viosey/hexo-theme-material/blob/master/layout/_widget/page-links.ejs
然后自己创了一个link.ejs
```
<%- partial('_partial/header', {
    title: locals.title || theme.link_title,
    hdClass: 'link-header'
}) %>
<div class="container body-wrap">
<%- partial('_partial/page-links.ejs', {pagination: config.link, index: false}) %>
<%- partial('_partial/paginator') %>
</div>
```

部署上去后， 友情链接界面底部是没有靠拢的，尤其是浏览器宽度拉小，长度拉长后，空白区域会越来越大
https://jerryc.me/link/

![image](https://user-images.githubusercontent.com/16351105/42727448-72c30d3a-87d9-11e8-921a-f70b09a1c007.png)
![image](https://user-images.githubusercontent.com/16351105/42727458-919f4412-87d9-11e8-924b-2687b2d41203.png)
请求大神帮忙，如何解决这个问题

**Comment by Waitung** [comment]
尝试一下改小\themes\indigo\source\css\_partial\layout.less文件里127行的“340”这个数。
` min-height: ~'calc(100vh - 340px)';`
