### ISSUE TITLE
Home页文章概览，每篇文章内容显示完了才显示more按钮

### ISSUE THREAD

**Issue by jianglan-dev** [yscoder/hexo-theme-indigo#43]
你好，
我配置好之后，发现Home页列出的文章显示了所有内容，而不是只显示一小部分内容。另外，建议在文章详情页中的导航栏再往右边靠一点，使文章有更多的空间显示！
谢谢！

**Comment by yscoder** [comment]
see #7

**Comment by jianglan-dev** [comment]
Thx，另外，详情页中的导航栏可以控制往右移一点吗？

**Comment by yscoder** [comment]
你可以修改 `source/css/_partial/layout/.less` 中 169 行，调整 width 数值。
但需要注意对不同屏幕尺寸的适配，能适配到笔记本的宽度 1366 就可以。再小的宽度有响应式控制，无需考虑。

**Comment by jianglan-dev** [comment]
非常感谢！
