### ISSUE TITLE
背景颜色加载失败

### ISSUE THREAD

**Issue by WenQizhaNg1** [yscoder/hexo-theme-indigo#431]
按照issues中的指引找到了variable.less文件，更改颜色后在http://localhost:4000/ 成功预览，但是执行
  hexo clean ，   hexo g -d后博客打开依然为默认原色，求解

**Comment by ZekeRed** [comment]
同求

**Comment by MengChatChat** [comment]
# 设置为 true 发布后将使用 unpkg cdn 最新的主题样式
# 如果想让你的自定义样式生效，把此项设为 false
cdn: false

**Comment by MengChatChat** [comment]
设置为 true 发布后将使用 unpkg cdn 最新的主题样式。如果想让你的自定义样式生效，把此项设为 false。
cdn: false

**Comment by Tanky-Zhang** [comment]
> 设置为 true 发布后将使用 unpkg cdn 最新的主题样式。如果想让你的自定义样式生效，把此项设为 false。
> cdn: false

**Comment by Tanky-Zhang** [comment]
> 设置为 true 发布后将使用 unpkg cdn 最新的主题样式。如果想让你的自定义样式生效，把此项设为 false。
> cdn: false

我遇到了改为cdn：false以后整个博客的样式都没有了，请问这怎么处理
