### ISSUE TITLE
请问怎么添加自己的在网页标签tittle左边显示的icon

### ISSUE THREAD

**Issue by mahaozhe** [yscoder/hexo-theme-indigo#436]
请问怎么添加自己的在网页标签tittle左边显示的icon呢？就像大神这个斜放的S型图标

**Comment by Sogrey** [comment]
在根目录下`_config.yml`文件配置
![image](https://user-images.githubusercontent.com/8125441/47889215-ce6afc00-de83-11e8-91db-19cca343a93c.png)

申城页面时 head标签下会多下面一句
\<link rel="shortcut icon" href="/favicon.ico"\>

favicon.ico 这个文件放在 source目录下
