### ISSUE TITLE
如何给文章添加tags和categories呢

### ISSUE THREAD

**Issue by mahaozhe** [yscoder/hexo-theme-indigo#437]
我按照这种方法添加了之后在博客中并没有分类和目录，就是没有对应的标签和分类，只有一个“全部”分类

﻿﻿---
title: Hello World
tags: 
- test1
- test2
categories: hello
---

**Comment by Sogrey** [comment]
![image](https://user-images.githubusercontent.com/8125441/47890841-b4cdb280-de8b-11e8-9ebc-ec1fbb171033.png)

**Comment by mahaozhe** [comment]
我确实这样写了，但是仿佛还是不可以，是不是还有别的地方需要配置呢？谢谢您了

![1](https://user-images.githubusercontent.com/32680846/47891505-74bbff00-de8e-11e8-9154-7788c63d5f51.png)
![2](https://user-images.githubusercontent.com/32680846/47891506-74bbff00-de8e-11e8-872d-4deb528f3a75.png)

**Comment by mahaozhe** [comment]
解决了，是markdown编辑器的问题，大家不要用windows10 的 markdown for windows10
