### ISSUE TITLE
关于搜索功能与构建的疑问

### ISSUE THREAD

**Issue by bi-kai** [yscoder/hexo-theme-indigo#45]
1、在内网环境使用hexo，用户没有外网权限，所以不能用swiftype，问下你的json方式，能完全离线使用么？或者能否简要描述下它的工作过程？
2、后续是否考虑引入代码合并压缩等的构建？

**Comment by yscoder** [comment]
1. 完全可以。所有文章数据都序列化到这个 JSON 文件中，把它当作一个“数据源”，发布站点的时候这个文件也会跟随发布，所以可以轻易的解析数据进行查询（其实就是遍历筛选）。
2. 合并压缩这些已经有诸多可用的插件了，https://hexo.io/plugins/。

**Comment by bi-kai** [comment]
ok
