### ISSUE TITLE
关于左侧图标及文字间距

### ISSUE THREAD

**Issue by 2hf** [yscoder/hexo-theme-indigo#46]
除了tags之外，其他的间距都是48.58或者是50，但是就是tag是51.44，明显看着和其他文字不在同一垂线上……这个能修复嘛？图片上传不了，可以看下博客的左侧。

**Comment by 2hf** [comment]
另外一个问题:

我在本地添加了一个link页面，修改了frontawsome.less，本地起hexo s是可以看到图标的，但是[我的博客](http://elbarco.cn/) 上却看不到。我查看了提交的代码，与本地变更一致。关掉了任何的adblock工具，并且清除了本地缓存，但是图标依旧没展示。还有可能是什么原因吗？

**Comment by yscoder** [comment]
问题1：

可以修复。但是你的主题跟现在的版本不一致，很多页面样式有了修改。如果你不想更新到最新的话，问题修复后需要你手动对比 css文件更改。
不过，也不需要改几行。

---
问题2:

你需要查看 public 目录下的 css 文件，看看样式有没有更新（搜索 `icon-links`）。
如果没有找到，执行 `hexo clean`，再重新生成上传。

**Comment by 2hf** [comment]
问题1：我还是手动修改好了……最开始搭建的时候也没少动主题样式，不过已经记不清改了什么……（悲伤的表情）
问题2：hexo clean之后重新生成即可，已经修复……

十分感谢~

**Comment by 2hf** [comment]
这里再抛出一个问题3，刚刚发现的：

在主页上，是可以看到links页面，但是进入文章后，在唤出左侧菜单，发现links链接不见了……这是什么问题导致呢？

**Comment by 2hf** [comment]
关于看不到文章这个，我改了left-col.ejs里的这一段代码：
```
 var menuItem, isActive = function(item) {
          return (is_home() && item === 'home') || (item === 'links') || (is_archive() && item === 'archives') || ( (is_tag() || page.type === 'tags') && item === 'tags');
      };
```
就可以看到了。有个疑问是，is_home()和其他的is_archive()是在哪定义的呢？ 我对hexo主题样式神马的是一点都不懂……摸索尝试中……

**Comment by yscoder** [comment]
is_home() 和 is_archive() 是 Hexo 内置的辅助函数，在文档中可以找到。
https://hexo.io/zh-cn/docs/helpers.html

**Comment by yscoder** [comment]
图标间距的 css 更改已提交，看 `layout.less` 的更改。

**Comment by 2hf** [comment]
两个字：完美  👍
