### ISSUE TITLE
如何自定义页面

### ISSUE THREAD

**Issue by zh-f** [yscoder/hexo-theme-indigo#47]
增加了Link页，如何自定义页面布局和内容呢？
比如去掉我[友情链接页面](http://elbarco.cn/links/)这个页面右侧的分享，将这个页面布局改成Tag的样子——大标题和链接地址。
求指教~

**Comment by yscoder** [comment]
看你这么能折腾，可以考虑自建布局页。

1. 在你的友情链接页面顶部加个 `layout: links`；
2. 在主题 layout 目录下建个 links.ejs

好了，这个 ejs 文件你随便折腾，生成的页面会包含 头部 和 左侧菜单。

**Comment by 2hf** [comment]
=.= 好，这个我去试试……现在怎么才能让links像tags页面被点击后menu有被选中的css样式呢？
我尝试了is_current(path, [strict])：
```
var menuItem, isActive = function(item) {
          return (is_home() && item === 'home') || (is_current("/links") && item === 'links') || (is_archive() && item === 'archives') || ( (is_tag() || page.type === 'tags') && item === 'tags');
```
但是并没有被选中的样式……有点懵 :sweat_smile:

**Comment by yscoder** [comment]
把 `/` 去掉试试

**Comment by yscoder** [comment]
改成这个吧，一劳永逸。
```
return url_for(item.url) === '/' + page.path;
```

**Comment by 2hf** [comment]
已经根据你的commit完成了修改，强迫症的需求得到了满足，刷一波6666…… 😄

**Comment by athrunsun** [comment]
@yscoder 你好，可以提供一下https://imys.net/custom/ 的源代码吗？

**Comment by OldBeLight** [comment]
@yscoder 同求https://imys.net/custom/ 的源代码

**Comment by yscoder** [comment]
[自定义页面](https://github.com/yscoder/hexo-theme-indigo/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E9%A1%B5%E9%9D%A2)
