### ISSUE TITLE
生成的<a/>标签都带有 target='_blank' （包括分享的按钮）

### ISSUE THREAD

**Issue by spartguo** [yscoder/hexo-theme-indigo#485]
主页的导航栏关闭的×按钮，以及搜索按钮，分享按钮，每次点击出现动画前都会新打开一个about:blank#blocked页面。查看html发现相应的<a标签中都有target='_blank'。全部删除按照文档一步步来一遍生成的html依然如此，是不是需要改哪里的配置呢？望大神们指点。

**Comment by anyaoqi** [comment]
我也遇到了 ，求解决方法

**Comment by anyaoqi** [comment]
我找到解决方法了。
可能是在编译的时候默认把a标签的target属性自动补上了，要是a标签本身就有target这个属性就不会往上加了

菜单关闭按钮
1.打开` themes\indigo\layout\_partial\menu.ejs
2.找到 id="menu-off" 的a标签
3.在a标签上新增 target="" 

右侧分享按钮
1.打开 `themes\indigo\layout\_partial\header.ejs
2.找到 id="menuShare" 的a标签
3.在a标签上新增 target=""

**Comment by spartguo** [comment]
哇，原来是这样，感谢大佬！
