### ISSUE TITLE
请问为什么文章标题显示为No Title ?

### ISSUE THREAD

**Issue by maple-zyf** [yscoder/hexo-theme-indigo#49]
我是用org-mode编写的文档，　然后导出为html，可是标题显示no title
![selection_026](https://cloud.githubusercontent.com/assets/12221812/16654161/16b61a42-4487-11e6-9110-db09e4a16fff.png)
[这是网站地址](https://maple-zyf.github.io/)

**Comment by yscoder** [comment]
文章格式如下：
```
title: Test
date: 2016-07-08 11:22:02
tags: [ a, b, c]
description: 这是一篇测试文章
---
文章正文
```

如果 `title` 为空，或格式有误，就会显示 `No Title`。

**Comment by maple-zyf** [comment]
谢谢

2016-07-08 11:24 GMT+08:00 Yusen <notifications@github.com>:

**Comment by zengxiaozeng** [comment]
请问下 在文章的标题页里面的内容描述  为什么会显示一大堆的数字？https://zengxiaozeng.github.io/

**Comment by yscoder** [comment]
@zengxiaozeng 文章摘要是截取的部分文章内容去标签后输出的，那些数字是内容里的代码行号。
