### ISSUE TITLE
我尝试修改css/_partial/article.less但是没有效果，已经执行了hexo clean和hexo g

### ISSUE THREAD

**Issue by di404** [yscoder/hexo-theme-indigo#492]
我想修改代码块部分的行间距，于是修改了post-content table tr，但是重新生成后没有效果，我尝试修改了article.less中的post card，也没有效果，是我的做法有问题吗

**Comment by yrpang** [comment]
是不是[这个](https://github.com/yscoder/hexo-theme-indigo/wiki/常见问题#更改样式后网站没有生效)问题

**Comment by di404** [comment]
cdn设为false就可以了

**Comment by di404** [comment]
是的 感谢回复

发自我的iPhone

**Comment by di404** [comment]
发自我的iPhone
