### ISSUE TITLE
[Bug]显示侧边栏的功能在微信中存在闪关现象

### ISSUE THREAD

**Issue by Phoenix-Ans** [yscoder/hexo-theme-indigo#5]
[步骤]
1.分享博客链接到微信
2.微信用户打开该链接，点击显示侧边栏按钮
[结果]
侧边栏显示后即刻关闭，无法固定显示
[期望]
可固定显示侧边栏，在点击关闭后，侧边栏方关闭

**Comment by yscoder** [comment]
我测试了我的博客，没有发现这种情况。微信6.3.13 for Android
提供下你发生问题的页面地址和使用环境，我再进一步测试。

**Comment by Phoenix-Ans** [comment]
发生问题的页面地址微信分享Url "http://phoenix-ans.github.io/?from=singlemessage&isappinstalled=0"
原始博客地址Url “http://phoenix-ans.github.io”
微信版本 WeChat 6.3.15 for iOS

**Comment by hewz** [comment]
iOS应用中打开网页确实会出现这种情况.
iOS9.3.1 Safari打开没问题，微博中打开Menu会闪退，并且界面跳回主页。

**Comment by hewz** [comment]
另外Mac Chrome不显示menu中 github的图标，其它浏览器正常，很奇怪..
