### ISSUE TITLE
Cannot GET /tags/

### ISSUE THREAD

**Issue by Shineee** [yscoder/hexo-theme-indigo#51]
![qq 20160713114731](https://cloud.githubusercontent.com/assets/2569939/16791260/ba40f1b6-48ef-11e6-837e-fb18a95528ac.png)
这个是什么问题？

**Comment by yscoder** [comment]
见：[开启标签页](https://github.com/yscoder/hexo-theme-indigo/wiki/%E5%AE%89%E8%A3%85#%E5%BC%80%E5%90%AF%E6%A0%87%E7%AD%BE%E9%A1%B5)

**Comment by Shineee** [comment]
source\tags\index.md
要把老数据替换掉，不能留
然后，用下面的代码覆盖
layout: tags
noDate: true
comments: false
