### ISSUE TITLE
TypeError: Cannot read property 'offset' of null

### ISSUE THREAD

**Issue by Shineee** [yscoder/hexo-theme-indigo#52]
hexo generate和hexo server都会出现这个问题，是不是我哪里弄错了？
![qq 20160713114545](https://cloud.githubusercontent.com/assets/2569939/16791278/fe3a0ede-48ef-11e6-9f19-14afb0bf09ff.png)

**Comment by yscoder** [comment]
`hexo/_config.yml` 中的  `timezone`  配置是什么

**Comment by Shineee** [comment]
source\tags\index.md
要把老数据替换掉，不能留
然后，用下面的代码覆盖
layout: tags
noDate: true
comments: false
