### ISSUE TITLE
文章如何添加多个标签

### ISSUE THREAD

**Issue by Shineee** [yscoder/hexo-theme-indigo#53]
文章如何添加多个标签

有两种多标签格式

tags: [a, b, c]
或

tags: 
  - a
  - b
  - c

这个没说编辑哪个文件啊？有点蒙圈，试了好几个文件都不行，望指点，谢谢

**Comment by yscoder** [comment]
markdown 文件顶部的元数据。
```
title: test
date: 2016-07-13 16:13:26
tags: [a, b, c]
---
```

**Comment by Shineee** [comment]
---
tags:[Android, SQLite, Activity, Intent, Service, AndroidStudio]
layout:tags
noDate:true
comments:false
title:test
---
index.md 改成这样写了之后，没有生成tag页，public/tags 里面只有一个index.html

**Comment by yscoder** [comment]
tags 是定义在每篇文章的元数据中，也就是 `source/_posts/xxx.md` 。

**Comment by yscoder** [comment]
顶部的 `---` 不需要

**Comment by Shineee** [comment]
解决了，谢谢
