### ISSUE TITLE
首页菜单按钮问题

### ISSUE THREAD

**Issue by lionel0806** [yscoder/hexo-theme-indigo#54]
你好，进入首页点击隐藏菜单后，打开菜单按钮消失，左上角出现错误码如下图：
![2016-07-13 22 19 30](https://cloud.githubusercontent.com/assets/5477690/16806811/a46ccee2-4948-11e6-90aa-02c6c2eae56f.png)
请问这是什么问题啊？

**Comment by yscoder** [comment]
看起来模版有问题，重新 pull 下项目试试。

**Comment by lionel0806** [comment]
谢谢！pull了最新代码，问题依然存在

**Comment by yscoder** [comment]
有没有可供查看的线上地址？

**Comment by lionel0806** [comment]
@yscoder http://lionel0806.github.io/

**Comment by yscoder** [comment]
好的，我知道原因了。等我提交 fix 后，你在更新下项目就可以了。

**Comment by lionel0806** [comment]
已OK， Thank you！
