### ISSUE TITLE
search.js 搜索时报错

### ISSUE THREAD

**Issue by Shineee** [yscoder/hexo-theme-indigo#55]
```
loadData(function(data) {

            var result = data.filter(function(post) {
                return matcher(post, regExp);
            });

            render(result);
            Control.show();
        });
```

**error:**
Uncaught TypeError: data.filter is not a function

**Comment by yscoder** [comment]
编辑 `hexo/_config.yml`，添加 [json-content配置](https://github.com/yscoder/hexo-theme-indigo/wiki/%E9%85%8D%E7%BD%AE#jsoncontent%E9%85%8D%E7%BD%AE)，重新生成下。

**Comment by Shineee** [comment]
解决
