### ISSUE TITLE
标签页面空白

### ISSUE THREAD

**Issue by AllenChow** [yscoder/hexo-theme-indigo#56]
tags文件夹的md已经加了type的

type: "tags"

我已经加了一个标签，但是tag生成的页面没有任何标签，是空白的页面，求大神解答

**Comment by yscoder** [comment]
看看 `package.json` 中的版本号， 0.4.x 开始，标签页的配置做了更改，改为 `layout: tags`。

[更新日志](https://github.com/yscoder/hexo-theme-indigo/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#041)

**Comment by xuby0615** [comment]
我提交时 显示
`Unhandled rejection TypeError: D:\hexo\blog\themes\indigo\layout\archive.ejs:1
 >> 1| <%
    2|     var posts = [];
    3|     page.posts.each(function(post){
    4|         posts.push(post);
Cannot read property 'each' of undefined`
这个错误，要怎么解决？？

**Comment by AllenChow** [comment]
加了可以了。不过还有个问题，不知道为什么标签页面的标题下面会有时间显示，我看你的博客都是直接显示标题和子标题的。这个是我的标签站点。http://www.coderchow.com/tags/

**Comment by yscoder** [comment]
添加 `noDate: true`，没有日期时就显示子标题了。

**Comment by AllenChow** [comment]
可以了，万分感谢🙏

**Comment by yzytmac** [comment]
牛逼,谢谢了,我也是换了layout:tags才解决
