### ISSUE TITLE
提交时提示错误

### ISSUE THREAD

**Issue by xuby0615** [yscoder/hexo-theme-indigo#57]
用hexo d -g提交时，提示：
Unhandled rejection TypeError: D:\hexo\blog\themes\indigo\layout\archive.ejs:1
 >> 1| <%
    2|     var posts = [];
    3|     page.posts.each(function(post){
    4|         posts.push(post);

Cannot read property 'each' of undefined

这个错误，要怎么办？

@yscoder

**Comment by yscoder** [comment]
是不是你的文章数量为 0 ？另外 hexo 版本是多少？

**Comment by xuby0615** [comment]
@yscoder 

版本是3.2.2，文章数量不是0篇

**Comment by yscoder** [comment]
我升级到 3.2.2 没有这个错误。在 hexo server 中会报错吗？

**Comment by xuby0615** [comment]
没有 只在提交的时候 会有这个问题

@yscoder

**Comment by yscoder** [comment]
执行 `hexo clean` 再生成试试，如果不行就把 `hexo g --debug` 的日志放上来看看

**Comment by xuby0615** [comment]
@yscoder 

还是一样的错误。。。

**Comment by yscoder** [comment]
重新 `hexo init` 一个目录试试吧，暂时不知道是什么问题
https://github.com/hexojs/hexo/issues/1785
