### ISSUE TITLE
为什么我的显示是这样的

### ISSUE THREAD

**Issue by sakurajiang** [yscoder/hexo-theme-indigo#58]
我的github地址 http://sakurajiang.github.io/ ，能帮我看看为什么吗？我对前端不熟，谢谢

**Comment by sakurajiang** [comment]
谢谢

**Comment by yscoder** [comment]
[生成站点后没有样式](https://github.com/yscoder/hexo-theme-indigo/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#%E7%94%9F%E6%88%90%E7%AB%99%E7%82%B9%E5%90%8E%E6%B2%A1%E6%9C%89%E6%A0%B7%E5%BC%8F )
