### ISSUE TITLE
你好，谢谢你昨天回答我的问题，已经解决好了，但是为什么我用****加粗语法后在网页上会加粗但是同时会有红色的横线

### ISSUE THREAD

**Issue by sakurajiang** [yscoder/hexo-theme-indigo#59]

**Comment by yscoder** [comment]
是 css 设置的。如果不需要，可以删除该文件 `source/css/_partial/article.less` 中第 109 行。

**Comment by sakurajiang** [comment]
谢谢，请问为什么我应该在哪修改才能改变原来网页显示的样子，我在public文件夹下的index上修改没有用呀

**Comment by yscoder** [comment]
source & layout 目录下，这里是源文件，public 目录的内容都是根据源文件生成的。
