### ISSUE TITLE
关于<!-- more -->标签

### ISSUE THREAD

**Issue by glassweichao** [yscoder/hexo-theme-indigo#60]
如果使用 折叠的话，是否能在主页的文章列表项末尾加上 <read more>的标签或按钮，让读者更好的知道是否该展开阅读。
谢谢！

**Comment by yscoder** [comment]
最初是有一个 MORE 按钮的，从  [886f015](https://github.com/yscoder/hexo-theme-indigo/tree/886f015652b381cdf6ad5f417c0f4be7779109c4) 之后就被我干掉了。你要相信会去看博客的用户是一定知道文章摘要的概念和点击文章标题可以进入详情页的操作。

那个按钮的样式目前还没有删除，你如果需要的话，可以自行修改模版。把下面这一句加到 `/layout/_partial/index-item.ejs` 中的某个位置。
```
<a href="<%- url_for(post.path) %>" class="post-more waves-effect waves-button waves-light">MORE</a>
```

**Comment by ky0ncheng** [comment]
https://design.google.com/articles/evolving-the-google-identity/

文章內頁設計可以試試看google的這個

**Comment by yscoder** [comment]
@glassweichao 

文章摘要现改为纯文字形式渲染，并增加“阅读全文”跳转链接。[v0.4.4](https://github.com/yscoder/hexo-theme-indigo/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#044)

![image](https://cloud.githubusercontent.com/assets/12295378/17612345/64e6f6e2-6083-11e6-97ba-0b6387dd9514.png)
