### ISSUE TITLE
markdown代码块 行号和代码不匹配 错位

### ISSUE THREAD

**Issue by CmcnPro** [yscoder/hexo-theme-indigo#62]
详见http://ygin.pro/Duoshuo-CSS/

**Comment by yscoder** [comment]
我查阅了相关 css 没有找到问题，便把代码复制到我博客中测试，结果如下：

http://7ximpj.com1.z0.glb.clouddn.com/bug-code-line-number.png

可以发现，同样的代码我的博客中渲染为 248 行，你的是 253 行，如果你的排版格式没有问题的话，那就是 Hexo 渲染导致的。
尝试把 `hexo-renderer-marked` 、`hexo-util` 更新到最新版本试试。

**Comment by CmcnPro** [comment]
找到问题了，代码块里代码的问题，用从chrome复制的，就正常渲染，如果用本地的代码就会出现这个问题。可能本地的代码里有什么特殊的东西

**Comment by yscoder** [comment]
也许是 `\r\n` 吧
