### ISSUE TITLE
最新版本 首页格式没有了..

### ISSUE THREAD

**Issue by onweer** [yscoder/hexo-theme-indigo#66]
首页markdown格式都没有了,全都挤在一起了.

**Comment by yscoder** [comment]
> 那一天，文章摘要终于回想起了曾一度被HTML格式化的那份惊慌。

现在的情况不正是还原了文章摘要原本的模样吗？

**Comment by onweer** [comment]
0 0... 代码都挤在一起了 /(ㄒoㄒ)/~~  ,大夏天的热啊

**Comment by yscoder** [comment]
所以才要阅读全文啊。

后面我会增加一个配置项，自由选择是否格式化。

**Comment by onweer** [comment]
(⊙v⊙)嗯, 先回到0.4.3了~

**Comment by lengthmin** [comment]
希望尽快更新的说。。

**Comment by yscoder** [comment]
已增加新的配置项：`excerpt_render: false`，为 `true` 时将渲染为 `html`。
