### ISSUE TITLE
disqus无法加载

### ISSUE THREAD

**Issue by XiaochenCui** [yscoder/hexo-theme-indigo#68]
[错误页面](http://www.cuixiaochen.com/2016/08/18/N%E7%9A%87%E5%90%8E%E9%97%AE%E9%A2%98%E8%A7%A3%E6%B3%95%E6%B1%87%E6%80%BB%E5%8F%8A%E5%88%86%E6%9E%90-python/)
页面报错：
We were unable to load Disqus. If you are a moderator please see our troubleshooting guide.
console报错：
lookup.js:279 Uncaught SecurityError: Blocked a frame with origin "http://disqus.com" from accessing a frame with origin "http://www.cuixiaochen.com". Protocols, domains, and ports must match.

**Comment by XiaochenCui** [comment]
是chrome浏览器的问题吗

**Comment by yscoder** [comment]
你的 `disqus_shortname` 应该是在主题配置中，模版中引用的是站点配置，已fix。
