### ISSUE TITLE
你好 请问博客长度怎么控制

### ISSUE THREAD

**Issue by jinnchen** [yscoder/hexo-theme-indigo#7]
我使用了你的代码，修改了颜色的配置，然后放了篇markdown写的文章上去，发现主页把所有内容都加载出来，请问怎么修改？

**Comment by yscoder** [comment]
在Markdown文件中需要分隔的地方加`<!--more-->`，首页只显示该标记之前的内容。

**Comment by jinnchen** [comment]
thanks

**Comment by jinnchen** [comment]
thank you

**Comment by yscoder** [comment]
标签页是一个自定义页面，需要手动添加。

* 生成标签页

`hexo new page tags`

* 修改`hexo/source/tags/index.md`的页面配置
```
type: "tags"
noDate: true
comments: false
---
```

**Comment by chiahaolu** [comment]
我也遇到无法打开tag目录，按照你的方法也无法解决。

**Comment by jinnchen** [comment]
哦哦 我懂了 谢谢

**Comment by jinnchen** [comment]
突然发现README.md原来有写。。。不好意思了
