### ISSUE TITLE
引入代码中如果有换号会自动取消,但是在代码的顶部和尾部会放入大量的换行

### ISSUE THREAD

**Issue by itdais** [yscoder/hexo-theme-indigo#71]
在引入java代码中,为了规范代码,有一些换行间隙,如引用代码里有十条换行,
那么在网页中显示头部和尾部都会有大量换行,但是中间的换行没有了

**Comment by itdais** [comment]
具体可以看我的代码引用,在头部和尾部的时候都添加了4行无用的换行http://itdais.com/2016/08/25/SwipeToRefresh%E6%BB%91%E5%8A%A8%E5%86%B2%E7%AA%81%E8%A7%A3%E5%86%B3/

**Comment by yscoder** [comment]
已修复
