### ISSUE TITLE
Material design icon

### ISSUE THREAD

**Issue by SSARCandy** [yscoder/hexo-theme-indigo#74]
用 [Material design icon](https://design.google.com/icons/) 會比較符合整體風格吧

**Comment by SSARCandy** [comment]
https://ssarcandy.tw/

我自己的作法是混搭，因為像是 github 之類的就沒有對應的 material icon
看看大神是否要參考

**Comment by yscoder** [comment]
常见的界面图标，两个图标库都有。
之所以用 fa 就是看中其社交、品牌标志类的图标较多。用户（你们）使用图标的场景一般就是左侧菜单了，fa 可以满足大多数人需求。

图标还是易集成的，你们也完全可以自己去字体图标平台定制自己需求的。
