### ISSUE TITLE
the Rights to modify your theme

### ISSUE THREAD

**Issue by Will-Cui** [yscoder/hexo-theme-indigo#75]
我使用了你的主题:hexo-theme-indigo。
我想改一下footer的内容，查了一下Creative Commons的内容，还是不太确定可不可以去掉指向你的github的链接？
可以去掉吗？（如下图）
我想放一句名言警句或者座右铭之类的。
![screenshot](https://cloud.githubusercontent.com/assets/21967575/18226698/2cf1efd2-7242-11e6-9ec7-277cf318ddba.png)

**Comment by yscoder** [comment]
CC 协议是面向你的博客内容的，表示博客内容转载使用需署名、非商业使用、可修改但需保持原协议。
而这个博客主题完全是开源的，没有加任何 license 限制，随便你怎么折腾。
