### ISSUE TITLE
话说，有没有考虑添加百度统计……

### ISSUE THREAD

**Issue by 2hf** [yscoder/hexo-theme-indigo#79]
今早例行打开CNZZ查看网站统计，然后遇到了CNZZ的问题，提示我并非总管理员，沟通客服之后说正在修复，于是我弄了个Google Analytics，但是js貌似一直加载不出来。

所以有这么一个想法：有没有考虑增加百度统计呢……:smile:

**Comment by yscoder** [comment]
你明明可以自己搞定再给我一个 PR 啊ヽ(●-`Д´-)ノ

**Comment by 2hf** [comment]
:joy:……偷懒被发现了_(:зゝ∠)_
还有啊，怎么做一个打赏按钮呢…… :dollar:

**Comment by yscoder** [comment]
收款二维码是从哪儿生成的，你知道吗？

**Comment by yscoder** [comment]
我找到了，回头加上打赏，二维码需要用户提供。

**Comment by 2hf** [comment]
嗯嗯，坐等…我身边有同事自己的博客是挂了一个微信的，也可以考虑下支付 包的？：）

**Comment by yscoder** [comment]
ok
