### ISSUE TITLE
如何自定义左侧菜单选项？

### ISSUE THREAD

**Issue by hayukleung** [yscoder/hexo-theme-indigo#8]
除了默认的Home\Archive\Tags\GitHub\Weibo\Link菜单项，我想要自定义增加额外的菜单项。
我在_config.yml里menu下新增了，但是没有左侧的小logo，请问在哪里可以配置？

**Comment by yscoder** [comment]
你说的是菜单图标吧，如添加一个`facebook`链接：

```
facebook:          
    url: http://yourFacebookUrl
    target: _blank
```

那么你就需要添加一个对应的名为`facebook`的`Font Awesome`图标。

打开 `theme/indigo/source/css/_partial/fontawesome.less`，拉到最后一行，按格式添加你需要的图标。
如： `.@{fa-css-prefix}-facebook:before { content: @fa-var-facebook; }`

> 必须保证[Font Awesome图标集](http://fontawesome.io/icons/)中有你所需要的图标。

**Comment by hayukleung** [comment]
非常感谢！已解决。

**Comment by hayukleung** [comment]
我发现fontawesome icon尺寸不一致，会导致菜单的文字没法左对齐，不知道有没有好的解决方法？

**Comment by hayukleung** [comment]
搜索了下对fontawesome icon尺寸的统一方法，都说使用`fa-fw`class，于是查看了`fa-fw`的定义
```
.fa-fw {
  width: 1.28571429em;
  text-align: center;
}
```
在`theme/indigo/source/css/_partial/fontawesome.less`里找到
```
.@{fa-css-prefix} {
    display: inline-block;
    font-family: 'FontAwesome';
    font-size: 1em;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
```
补上`text-align: center;`属性即可。

**Comment by Bob-Yuan** [comment]
最新版本的menu 下增加link子属性怎么用的，没看懂注释，可以举个例子吗
https://github.com/yscoder/hexo-theme-indigo/wiki/配置#左侧菜单
