### ISSUE TITLE
文章标题过长时，进入文章详情后无法展开左栏

### ISSUE THREAD

**Issue by Phoenix-Ann** [yscoder/hexo-theme-indigo#80]
http://anna3.pub/2016/07/11/Translate.The-Automated-Testing-Handbook/

Title：The Automated Testing Handbook 自动化测试手册简介

**Comment by yscoder** [comment]
跟文章标题无关，是有 js 错误，昨天修复过了，你再更新下主题就可以了。

**Comment by Phoenix-Ann** [comment]
好的 谢谢~~ @yscoder
