### ISSUE TITLE
不知道为什么左边导航栏的footer没有像模板一样跑到底部？

### ISSUE THREAD

**Issue by leongfeng** [yscoder/hexo-theme-indigo#82]
如图，网址是 http://leongfeng.github.io 我没有改过样式
![qq 20160910222024](https://cloud.githubusercontent.com/assets/11471256/18411165/c5ac9d1e-77a4-11e6-8fbf-ec5ab68a5d79.png)

**Comment by yscoder** [comment]
你用的什么浏览器？

**Comment by leongfeng** [comment]
我试了一下，最新版的chrome(52)没问题，firefox也没问题，QQ浏览器(47)，chrome 31，IE 11 都有问题。
