### ISSUE TITLE
右侧目录不能点击跳转到指定锚

### ISSUE THREAD

**Issue by levingit** [yscoder/hexo-theme-indigo#85]
生成的toc目录，点击后不能定位到指定锚位置，这是为什么？

**Comment by yscoder** [comment]
可能是有特殊字符，发个页面链接我看看

**Comment by levingit** [comment]
@yscoder 
[http://ayard.top/English/20160801-English-symbols.html](http://ayard.top/English/20160801-English-symbols.html)

**Comment by levingit** [comment]
@yscoder   呃…………原来是firefox的问题　我换成chrome试了可以的……　因为一直用的firefox　所以这个问题其实发现好久了
