### ISSUE TITLE
文章页的本文地址显示错误

### ISSUE THREAD

**Issue by ukhack** [yscoder/hexo-theme-indigo#89]
我的地址是
>  https://ukhack.github.io/2016/10/11/Hi-Git/
但是生成的却是
> 本文地址： http://ukhack.github.com/2016/10/11/Hi-Git/
> [@Road of web](http://ukhack.github.com)
注意到上面的是.com所以是错误的。
请问这个问题在哪修复

**Comment by yscoder** [comment]
`hexo/_config.yml` -> `url: https://ukhack.github.io`
