### ISSUE TITLE
install好jsonContent之后运行报错

### ISSUE THREAD

**Issue by MJPiero** [yscoder/hexo-theme-indigo#92]
install好jsonContent之后运行报错。
内容是undefined is not a function
删掉这个组件就好了
这可能是什么原因呢
在线等！

**Comment by yscoder** [comment]
1. jsonContent 是否配置正确，[参考](https://github.com/yscoder/hexo-theme-indigo/wiki/%E9%85%8D%E7%BD%AE#jsoncontent%E9%85%8D%E7%BD%AE)
2. 浏览器报错还是控制台报错，最好给个截图

**Comment by MJPiero** [comment]
是在终端运行hexo server的时候就报错了。
页面就是报错找不到content.json
因为hexo server没有成功，没生成content.json
![](http://blog2.pierrothall.com/images/QQ%E6%88%AA%E5%9B%BE20161021165145.png)

**Comment by yscoder** [comment]
`hexo clean` 清除缓存试试，另外你的 _post 目录是否有文章，可能是博客没有文章导致某些变量值为空

**Comment by MJPiero** [comment]
hexo clean 试过了，目录里面有文章的，我看好像几乎没人出现这个问题，也是很奇怪

**Comment by yscoder** [comment]
嗯，你可以自己尝试排查下错误原因，error 已经定位到 `hexo-generator-json-content` 模块中的 `index.js:126` 行了

**Comment by yscoder** [comment]
你的node版本很低吗？

**Comment by MJPiero** [comment]
0.12.3

**Comment by yscoder** [comment]
你确实需要更新了~

**Comment by yscoder** [comment]
错误行的代码调用了一个 ES6 函数，你的 node 版本不支持

**Comment by MJPiero** [comment]
原来如此，T^T 我先改用hexo-generator-json了

**Comment by MJPiero** [comment]
谢谢大神T^T
