### ISSUE TITLE
url 内多了 "index.html"

### ISSUE THREAD

**Issue by xdcxdc** [yscoder/hexo-theme-indigo#97]
当前master分支：
- 文章底部本文地址处显示的url不带"index.html"，正常。
- `hexo new page`出来的页面底部显示的url多了"index.html"
- 分享按钮分享的 url 也多了"index.html"

card分支：
- 文章底部显示的url默认带"index.html"，但可通过修改_config.yml文件去掉。
- page页面与分享按钮的url都带了"index.html"

**Comment by yscoder** [comment]
* 文章的链接格式可以修改 `_config.yml: permalink` 配置项。
* `hexo new page [title]` 会建立一个 `source/[title]/index.md` 文件，通过路径映射后生成的 url 一定会带 `index.html`。如果不满意 `index.html`，就不要用 `new page` 命令，在 `source` 目录手动创建目录和文件。

**Comment by xdcxdc** [comment]
- card分支，custom page 的 `noDate: true` 被忽略了，显示了文件的更新日期。 master分支正常，title下面显示的是站点的subtitle。
- card分支，`_config.yml` `copyright` 内使用 `<%- page.permalink %>` 可以得到不带 `index.html` 的url。 但是生成的html内 `<meta property="og:url" content=` 内的 url 是带 `index.html` 的，能否修改为和 `page.permalink` 一致？ 以及 `<script> var BLOG_SHARE = { ..., url: "..." }; </script>` 内的url。master分支也有同样的问题。

**Comment by yscoder** [comment]
之前没注意过自定义页面，直接套用文章页模版看着有点不合适，你有什么好的建议吗？

类似于 `property="og:xx"` 和 `name="twitter:xx"` 的 `meta` 标签都是 hexo 函数生成的。

**Comment by xdcxdc** [comment]
我也没什么好的想法  ┑(￣Д ￣)┍

加 3 个功能建议：
- card 分支，Tags 页面下的 `全部` 标签页，目前显示每个标签对应的文章，会造成页面过长。可以考虑 `全部` 这一页放上一个 标签云 什么的，使用次数不同的标签大小不一样。
- card 分支，Archives/Tags/Categories 三个页面，上方的大标题，能否在`_config.yml` 内自定义。现在显示的都是英文。
- reward 功能，可否支持在md文件的头部加上 `reward: false` , 以在个别页面禁用打赏功能。
